/* Generated by convbdf on Fr 8. Jan 01:27:36 CET 2016. */
#include <gfx/font.h>

/* Font information:

   name: -FreeType-Erbos Draco 1st NBP-Medium-R-Normal--15-110-100-100-P-75-ISO10646-1
   pixel size: 15
   ascent: 8
   descent: 0
*/

/* Font character bitmap data. */
static const PROGMEM uint8_t font_draco_glyphs[] = {

/* Character (0x20): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, /* ******************************************************** */

/* Character (0x21): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xbe, 0xff, 0xff, 0xff, /* ************************ ***** ************************* */

/* Character (0x22): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xfe, 0xff, 0xfe, 0xff, 0xff, /* **************** *************** *********************** */

/* Character (0x23): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xfd, 0xff, 0xfd, 0xff, 0xff, /* ***************** *************** ********************** */

/* Character (0x24): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, /* ************************ ******************************* */

/* Character (0x25): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xed, 0xf7, 0xef, 0xff, 0xed, /* ***************** ** ****** ******** ************ ** *** */

/* Character (0x26): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xef, 0xf5, 0xae, 0xdd, 0xff, 0xbf, /* ************ **** * **** *** * ** *** **************** * */

/* Character (0x27): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, /* ************************ ******************************* */

/* Character (0x28): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfb, 0xdd, 0xff, 0xbe, /* ************************** ****** *** ********** ***** * */

/* Character (0x29): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xbe, 0xdd, 0xfb, 0xff, 0xff, 0xff, /* ******** ***** ** *** **** ***************************** */

/* Character (0x2a): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, /* ************************ ******************************* */

/* Character (0x2b): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfd, 0xff, 0xff, 0xff, /* ************************* ****************************** */

/* Character (0x2c): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xbf, 0xef, 0xff, 0xff, 0xff, 0xff, /* ************** ***** *********************************** */

/* Character (0x2d): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xf7, 0xff, 0xf7, /* *********************************** *************** **** */

/* Character (0x2e): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xdf, 0xff, 0xff, 0xff, 0xff, /* ********************* ********************************** */

/* Character (0x2f): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xdf, 0xef, 0xf7, 0xfb, 0xff, 0xfd, /* ************* ****** ****** ****** ************** ****** */

/* Character (0x30): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xdd, 0xff, 0xff, 0xbe, 0xff, 0xdd, /* ********* *** ****************** ***** ********** *** ** */

/* Character (0x31): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, /* ************************ ******************************* */

/* Character (0x32): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xdd, 0xef, 0xff, 0xf6, 0xff, 0xf9, /* ********* *** ****** *********** ** *************  ***** */

/* Character (0x33): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xb6, 0xff, 0xed, /* ********* ********************** ** ** ********** ** *** */

/* Character (0x34): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, /* ******************************** *********************** */

/* Character (0x35): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xbe, 0xff, 0xee, /* ********* ********************** ***** ********* *** *** */

/* Character (0x36): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xed, 0xff, 0xff, 0xbe, 0xff, 0xed, /* ********* ** ******************* ***** ********** ** *** */

/* Character (0x37): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xef, 0xf6, 0xff, 0xfc, /* ********* ****************** *** ** ************  ****** */

/* Character (0x38): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xed, 0xff, 0xff, 0xb6, 0xff, 0xed, /* ********* ** ******************* ** ** ********** ** *** */

/* Character (0x39): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xbe, 0xff, 0xed, /* ********* ********************** ***** ********** ** *** */

/* Character (0x3a): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xdd, 0xff, 0xff, 0xff, /* ************************* *** ************************** */

/* Character (0x3b): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xbf, 0xed, 0xff, 0xff, 0xff, /* ********************** ** ** *************************** */

/* Character (0x3c): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xf7, 0xeb, 0xdd, 0xff, 0xbe, /* ******************* ****** * **** *** ********** ***** * */

/* Character (0x3d): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xdb, 0xff, 0xdb, /* ********************************** ** ************ ** ** */

/* Character (0x3e): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xbe, 0xdd, 0xeb, 0xf7, 0xff, 0xff, /* ******** ***** ** *** **** * ****** ******************** */

/* Character (0x3f): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xbf, 0xf6, 0xff, 0xfd, /* ********* ******************** * ** ************* ****** */

/* Character (0x40): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xdd, 0xff, 0xff, 0xbe, 0xff, 0xbd, /* ********* *** ****************** ***** ********** **** * */

/* Character (0x41): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfb, 0xfd, 0xfe, 0xfd, 0xff, 0xfb, /* ********** ****** ****** ******** **************** ***** */

/* Character (0x42): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, /* ******************************** *********************** */

/* Character (0x43): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xbe, 0xff, 0xfd, /* ********* ********************** ***** ********** ****** */

/* Character (0x44): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, /* ************************ ******************************* */

/* Character (0x45): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xfe, /* ******************************** *************** ******* */

/* Character (0x46): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xfe, /* ******************************** *************** ******* */

/* Character (0x47): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xfe, 0xff, 0xfd, /* ********* ********************** **************** ****** */

/* Character (0x48): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xfe, /* ******** *************************************** ******* */

/* Character (0x49): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, /* ******************************** *********************** */

/* Character (0x4a): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xbf, 0xff, 0xfe, /* ************************************** ********* ******* */

/* Character (0x4b): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xfe, /* ******** *************************************** ******* */

/* Character (0x4c): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, /* ******** *********************************************** */

/* Character (0x4d): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xfe, /* ******** *************************************** ******* */

/* Character (0x4e): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xfe, /* ******** *************************************** ******* */

/* Character (0x4f): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xbe, 0xff, 0xfd, /* ********* ********************** ***** ********** ****** */

/* Character (0x50): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, /* ******************************** *********************** */

/* Character (0x51): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xfe, 0xff, 0xfd, /* ********* ********************** **************** ****** */

/* Character (0x52): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, /* ******************************** *********************** */

/* Character (0x53): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xff, 0xff, 0xb6, 0xff, 0xed, /* ********* ********************** ** ** ********** ** *** */

/* Character (0x54): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xfe, /* ******************************** *************** ******* */

/* Character (0x55): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xbf, 0xff, 0xfe, /* ******** ***************************** ********* ******* */

/* Character (0x56): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xdf, 0xbf, 0xdf, 0xff, 0xfe, /* ******** ************ ******** ****** ********** ******* */

/* Character (0x57): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xfe, /* ******** *************************************** ******* */

/* Character (0x58): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xde, 0xeb, 0xf7, 0xeb, 0xff, 0xde, /* ******** **** **** * ****** ****** * *********** **** ** */

/* Character (0x59): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xfe, /* ******** *************************************** ******* */

/* Character (0x5a): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xdf, 0xef, 0xf7, 0xfa, 0xff, 0xfc, /* ************* ****** ****** **** * *************  ****** */

/* Character (0x5b): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfe, 0xff, 0xfe, /* ******************************** *************** ******* */

/* Character (0x5c): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfd, 0xfb, 0xf7, 0xef, 0xff, 0xdf, /* ********* ******** ******** ******** **************** ** */

/* Character (0x5d): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, /* ************************ ******************************* */

/* Character (0x5e): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfb, 0xfd, 0xfe, 0xfd, 0xff, 0xfb, /* ********** ****** ****** ******** **************** ***** */

/* Character (0x5f): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xbf, 0xff, 0xbf, /* ************************************** *************** * */

/* Character (0x60): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xfe, 0xfd, 0xff, 0xff, 0xff, /* **************** ******** ****************************** */

/* Character (0x61): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfb, 0xff, 0xf7, /* ********************************** **************** **** */

/* Character (0x62): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, /* ******** *********************************************** */

/* Character (0x63): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xf7, 0xff, 0xff, 0xbb, 0xff, 0xf7, /* *********** ********************** *** ************ **** */

/* Character (0x64): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xfe, /* ************************************************ ******* */

/* Character (0x65): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xd7, 0xff, 0xff, 0xbb, 0xff, 0xf7, /* *********** * ******************** *** ************ **** */

/* Character (0x66): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xfd, 0xff, 0xfe, 0xff, 0xfd, /* ***************** ************** **************** ****** */

/* Character (0x67): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xf7, 0xff, 0xff, 0xbb, 0xff, 0xd7, /* *********** ********************** *** ************ * ** */

/* Character (0x68): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, /* ******** *********************************************** */

/* Character (0x69): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xf5, 0xff, 0xff, 0xff, /* ************************* * **************************** */

/* Character (0x6a): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xbb, 0xff, 0xf2, /* ********************************** *** ********* *  **** */

/* Character (0x6b): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfe, 0xff, 0xff, 0xff, 0xff, 0xff, /* ******** *********************************************** */

/* Character (0x6c): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xfe, 0xff, 0xbf, 0xff, 0xff, /* **************** ********************* ***************** */

/* Character (0x6d): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xfb, 0xff, 0xfb, 0xff, 0xff, /* ****************** *************** ********************* */

/* Character (0x6e): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfb, 0xff, 0xff, /* ********************************** ********************* */

/* Character (0x6f): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xf7, 0xff, 0xff, 0xbb, 0xff, 0xf7, /* *********** ********************** *** ************ **** */

/* Character (0x70): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfb, 0xff, 0xff, /* ********************************** ********************* */

/* Character (0x71): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfb, 0xff, 0xff, /* ********************************** ********************* */

/* Character (0x72): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xff, 0xfb, 0xff, 0xff, /* ********************************** ********************* */

/* Character (0x73): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xf7, 0xff, 0xff, 0xab, 0xff, 0xdb, /* *********** ********************** * * *********** ** ** */

/* Character (0x74): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfe, 0xff, 0xff, 0xff, /* ************************ ******************************* */

/* Character (0x75): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfb, 0xff, 0xff, 0xff, 0xff, 0xfb, /* ********** *************************************** ***** */

/* Character (0x76): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfb, 0xdf, 0xbf, 0xdf, 0xff, 0xfb, /* ********** ********** ******** ****** ************ ***** */

/* Character (0x77): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfb, 0xff, 0xff, 0xff, 0xff, 0xfb, /* ********** *************************************** ***** */

/* Character (0x78): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xbb, 0xd7, 0xef, 0xd7, 0xff, 0xbb, /* ********** *** **** * ****** ****** * ************ *** * */

/* Character (0x79): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xfb, 0xff, 0xff, 0xbf, 0xff, 0xdb, /* ********** *************************** *********** ** ** */

/* Character (0x7a): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xdf, 0xef, 0xfb, 0xff, 0xfb, /* ********************* ****** ***** *************** ***** */

/* Character (0x7b): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xf7, 0xed, 0xff, 0xbe, /* *************************** ***** ** *********** ***** * */

/* Character (0x7c): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xff, 0xff, 0xfd, 0xff, 0xff, 0xff, /* ************************* ****************************** */

/* Character (0x7d): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xbe, 0xed, 0xf7, 0xff, 0xff, 0xff, /* ******** ***** ** ** ****** **************************** */

/* Character (0x7e): bbw=7, bbh=9, bbx=0, bby=0, width=7 */
0xff, 0xf7, 0xfb, 0xf7, 0xef, 0xff, 0xf7, /* *********** ****** ******** ******** ************** **** */
};

/* Font structure definition. */
EXTERN_CONST Font font_draco =
{
	/* .glyph  = */ font_draco_glyphs,
	/* .name   =    "draco", */
	/* .width  = */ 7,
	/* .height = */ 8,
	/* .ascent =    8, */
	/* .first  = */ 32,
	/* .last   = */ 255,
	/* .offset = */ NULL,
	/* .width  = */ NULL,
};
