/* Generated by convbdf on Fr 8. Jan 22:04:25 CET 2016. */
#include <gfx/font.h>

/* Font information:

   name: -Adobe-Helvetica-Medium-R-Normal--8-80-75-75-P-46-ISO8859-2
   pixel size: 8
   ascent: 8
   descent: 2
*/

/* Font character bitmap data. */
static const PROGMEM uint8_t font_helvR8_glyphs[] = {

/* Character (0x00): bbw=5, bbh=5, bbx=1, bby=0, width=6 */
0x00, 0xa8, 0x00, 0x88, 0x00, 0xa8, /*            * * *           *   *           * * * */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            * * *           *   *           * * *             */

/* Character (0x20): bbw=1, bbh=1, bbx=0, bby=0, width=2 */
0x00, 0x00, /*                  */
0x00, 0x00, /*                      */

/* Character (0x21): bbw=1, bbh=6, bbx=1, bby=0, width=2 */
0x00, 0xbc, /*           **** * */
0x00, 0x00, /*           **** *     */

/* Character (0x22): bbw=3, bbh=3, bbx=1, bby=3, width=3 */
0x00, 0x1c, 0x00, /*           ***            */
0x00, 0x00, 0x00, /*           ***                  */

/* Character (0x23): bbw=5, bbh=5, bbx=0, bby=0, width=5 */
0x50, 0xf8, 0x50, 0xf8, 0x50, /*     * *    *****    * *    *****    * *  */
0x00, 0x00, 0x00, 0x00, 0x00, /*     * *    *****    * *    *****    * *            */

/* Character (0x24): bbw=4, bbh=7, bbx=1, bby=-1, width=5 */
0x00, 0x90, 0xa8, 0xac, 0x48, /*             *  *   * * *  ** * *   *  *  */
0x00, 0x00, 0x01, 0x00, 0x00, /*             *  *   * * *  ** * *   *  *     *      */

/* Character (0x25): bbw=6, bbh=6, bbx=1, bby=0, width=7 */
0x00, 0x1c, 0xd4, 0x2c, 0xd0, 0xac, 0xe0, /*           ***     * * **  ** *      * **  ** * *     *** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           ***     * * **  ** *      * **  ** * *     ***               */

/* Character (0x26): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0x68, 0x94, 0x68, 0xc0, 0xb0, /*            * **   * *  *   * **       **    ** * */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            * **   * *  *   * **       **    ** *             */

/* Character (0x27): bbw=1, bbh=2, bbx=0, bby=6, width=2 */
0x03, 0x00, /* **               */
0x00, 0x00, /* **                   */

/* Character (0x28): bbw=2, bbh=7, bbx=1, bby=-1, width=3 */
0x00, 0xf8, 0x04, /*            *****  *      */
0x00, 0x00, 0x01, /*            *****  *         *  */

/* Character (0x29): bbw=2, bbh=7, bbx=1, bby=-1, width=3 */
0x00, 0x04, 0xf8, /*           *        ***** */
0x00, 0x01, 0x00, /*           *        *****  *    */

/* Character (0x2a): bbw=3, bbh=3, bbx=1, bby=2, width=3 */
0x00, 0x10, 0x38, /*             *      ***   */
0x00, 0x00, 0x00, /*             *      ***         */

/* Character (0x2b): bbw=5, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x20, 0x20, 0xf8, 0x20, /*              *       *     *****     *   */
0x00, 0x00, 0x00, 0x00, 0x00, /*              *       *     *****     *             */

/* Character (0x2c): bbw=2, bbh=3, bbx=0, bby=-2, width=2 */
0x00, 0x80, /*                * */
0x02, 0x01, /*                * **  */

/* Character (0x2d): bbw=2, bbh=1, bbx=0, bby=2, width=3 */
0x20, 0x20, 0x00, /*      *       *           */
0x00, 0x00, 0x00, /*      *       *                 */

/* Character (0x2e): bbw=1, bbh=1, bbx=1, bby=0, width=2 */
0x00, 0x80, /*                * */
0x00, 0x00, /*                *     */

/* Character (0x2f): bbw=2, bbh=7, bbx=1, bby=-1, width=2 */
0x00, 0xe0, /*              *** */
0x00, 0x01, /*              ***  *  */

/* Character (0x30): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x84, 0x84, 0x78, /*            ****   *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  *    *   ****            */

/* Character (0x31): bbw=2, bbh=6, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x08, 0xfc, 0x00, /*                    *      ******         */
0x00, 0x00, 0x00, 0x00, 0x00, /*                    *      ******                   */

/* Character (0x32): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x88, 0xc4, 0xa4, 0x98, /*            *   *  *   **  *  * *   **  * */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *   *  *   **  *  * *   **  *           */

/* Character (0x33): bbw=3, bbh=6, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x94, 0x94, 0x68, /*                   * *  *  * *  *   * **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*                   * *  *  * *  *   * **            */

/* Character (0x34): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x20, 0x30, 0xfc, 0x20, /*              *      **    ******     *   */
0x00, 0x00, 0x00, 0x00, 0x00, /*              *      **    ******     *             */

/* Character (0x35): bbw=3, bbh=6, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x9c, 0x94, 0x64, /*                   ***  *  * *  *  *  **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*                   ***  *  * *  *  *  **            */

/* Character (0x36): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x94, 0x94, 0x64, /*            ****   * *  *  * *  *  *  **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   * *  *  * *  *  *  **            */

/* Character (0x37): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x04, 0xe4, 0x14, 0x0c, /*           *       *  ***  * *     **     */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *       *  ***  * *     **               */

/* Character (0x38): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x68, 0x94, 0x94, 0x68, /*            * **   * *  *  * *  *   * **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            * **   * *  *  * *  *   * **            */

/* Character (0x39): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x18, 0xa4, 0xa4, 0x78, /*            **     *  * *  *  * *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            **     *  * *  *  * *   ****            */

/* Character (0x3a): bbw=1, bbh=4, bbx=1, bby=0, width=2 */
0x00, 0x90, /*             *  * */
0x00, 0x00, /*             *  *     */

/* Character (0x3b): bbw=2, bbh=6, bbx=0, bby=-2, width=2 */
0x00, 0x90, /*             *  * */
0x02, 0x01, /*             *  * **  */

/* Character (0x3c): bbw=3, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x20, 0x50, 0x88, 0x00, /*              *      * *    *   *         */
0x00, 0x00, 0x00, 0x00, 0x00, /*              *      * *    *   *                   */

/* Character (0x3d): bbw=3, bbh=3, bbx=1, bby=1, width=4 */
0x00, 0x50, 0x50, 0x50, /*             * *     * *     * *  */
0x00, 0x00, 0x00, 0x00, /*             * *     * *     * *          */

/* Character (0x3e): bbw=3, bbh=5, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x88, 0x50, 0x20, /*                    *   *    * *      *   */
0x00, 0x00, 0x00, 0x00, 0x00, /*                    *   *    * *      *             */

/* Character (0x3f): bbw=3, bbh=5, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x08, 0xa8, 0x10, /*                    *       * * *    *    */
0x00, 0x00, 0x00, 0x00, 0x00, /*                    *       * * *    *              */

/* Character (0x40): bbw=8, bbh=7, bbx=1, bby=-1, width=9 */
0x00, 0xf0, 0x08, 0x24, 0x54, 0x54, 0x64, 0x44, 0x38, /*             ****   *      *  *    * * *   * * *   *  **   *   *    ***   */
0x00, 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, /*             ****   *      *  *    * * *   * * *   *  **   *   *    ***      * * * *        */

/* Character (0x41): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0xc0, 0x30, 0x2c, 0x30, 0xc0, /*               **    **    ** *      **        ** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*               **    **    ** *      **        **             */

/* Character (0x42): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x94, 0x94, 0x68, /*                   ******  * *  *  * *  *   * **  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******  * *  *  * *  *   * **              */

/* Character (0x43): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x84, 0x84, 0x84, 0x48, /*            ****   *    *  *    *  *    *   *  *  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  *    *  *    *   *  *              */

/* Character (0x44): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0xfc, 0x84, 0x84, 0x84, 0x78, /*           ******  *    *  *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           ******  *    *  *    *  *    *   ****              */

/* Character (0x45): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x94, 0x94, 0x84, /*                   ******  * *  *  * *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******  * *  *  * *  *  *    *             */

/* Character (0x46): bbw=4, bbh=6, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xfc, 0x14, 0x14, /*                   ******  * *     * *    */
0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******  * *     * *              */

/* Character (0x47): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x84, 0x84, 0x94, 0x70, /*            ****   *    *  *    *  * *  *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  *    *  * *  *    ***              */

/* Character (0x48): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0xfc, 0x10, 0x10, 0x10, 0xfc, /*           ******    *       *       *     ****** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           ******    *       *       *     ******             */

/* Character (0x49): bbw=1, bbh=6, bbx=1, bby=0, width=2 */
0x00, 0xfc, /*           ****** */
0x00, 0x00, /*           ******     */

/* Character (0x4a): bbw=3, bbh=6, bbx=1, bby=0, width=4 */
0x00, 0x40, 0x80, 0x7c, /*               *        *  *****  */
0x00, 0x00, 0x00, 0x00, /*               *        *  *****          */

/* Character (0x4b): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x30, 0x28, 0xc4, /*                   ******    **     * *    *   ** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******    **     * *    *   **             */

/* Character (0x4c): bbw=3, bbh=6, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xfc, 0x80, 0x80, /*                   ******       *       * */
0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******       *       *           */

/* Character (0x4d): bbw=5, bbh=6, bbx=2, bby=0, width=7 */
0x00, 0x00, 0xfc, 0x08, 0xf0, 0x08, 0xfc, /*                   ******   *        ****   *      ****** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******   *        ****   *      ******               */

/* Character (0x4e): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0xfc, 0x08, 0x30, 0x40, 0xfc, /*           ******   *        **        *   ****** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           ******   *        **        *   ******             */

/* Character (0x4f): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x84, 0x84, 0x84, 0x78, /*            ****   *    *  *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  *    *  *    *   ****              */

/* Character (0x50): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x24, 0x24, 0x18, /*                   ******  *  *    *  *     **    */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******  *  *    *  *     **                */

/* Character (0x51): bbw=5, bbh=8, bbx=1, bby=-2, width=6 */
0x00, 0x78, 0x84, 0x84, 0x84, 0x78, /*            ****   *    *  *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x01, 0x02, 0x00, /*            ****   *    *  *    *  *    *   ****       *  *   */

/* Character (0x52): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x24, 0x24, 0xd8, /*                   ******  *  *    *  *     ** ** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******  *  *    *  *     ** **             */

/* Character (0x53): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0x98, 0x94, 0x94, 0x64, /*                    **  *  * *  *  * *  *  *  **  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                    **  *  * *  *  * *  *  *  **              */

/* Character (0x54): bbw=3, bbh=6, bbx=1, bby=0, width=4 */
0x00, 0x04, 0xfc, 0x04, /*           *       ******  *      */
0x00, 0x00, 0x00, 0x00, /*           *       ******  *              */

/* Character (0x55): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0x7c, 0x80, 0x80, 0x80, 0x7c, /*           *****        *       *       *  *****  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           *****        *       *       *  *****              */

/* Character (0x56): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0x7c, 0x80, 0x40, 0x3c, /*                   *****        *      *   ****   */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   *****        *      *   ****               */

/* Character (0x57): bbw=7, bbh=6, bbx=1, bby=0, width=7 */
0x00, 0x1c, 0xe0, 0x20, 0x1c, 0xe0, 0x20, /*           ***        ***     *    ***        ***     *   */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           ***        ***     *    ***        ***     *                 */

/* Character (0x58): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xcc, 0x30, 0x30, 0xcc, /*                   **  **    **      **    **  ** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   **  **    **      **    **  **             */

/* Character (0x59): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0x04, 0x1c, 0xe0, 0x20, 0x1c, /*           *       ***        ***     *    ***    */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           *       ***        ***     *    ***                */

/* Character (0x5a): bbw=4, bbh=6, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xc4, 0xa4, 0x94, 0x8c, /*                   *   **  *  * *  * *  *  **   * */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   *   **  *  * *  * *  *  **   *             */

/* Character (0x5b): bbw=2, bbh=7, bbx=1, bby=-1, width=2 */
0xfc, 0x04, /*           ****** */
0x01, 0x01, /*           ******  *  */

/* Character (0x5c): bbw=2, bbh=7, bbx=0, bby=-1, width=2 */
0x1c, 0xe0, /*   ***        *** */
0x00, 0x01, /*   ***        ***  *  */

/* Character (0x5d): bbw=2, bbh=7, bbx=0, bby=-1, width=2 */
0x04, 0xfc, /*   *       ****** */
0x01, 0x01, /*   *       ******* *  */

/* Character (0x5e): bbw=5, bbh=3, bbx=0, bby=2, width=5 */
0x20, 0x10, 0x08, 0x10, 0x20, /*      *      *      *        *        *   */
0x00, 0x00, 0x00, 0x00, 0x00, /*      *      *      *        *        *             */

/* Character (0x5f): bbw=5, bbh=1, bbx=0, bby=-1, width=5 */
0x00, 0x00, 0x00, 0x00, 0x00, /*                                          */
0x01, 0x01, 0x01, 0x01, 0x01, /*                                         * * * * *  */

/* Character (0x60): bbw=2, bbh=2, bbx=0, bby=6, width=3 */
0x01, 0x02, 0x00, /* *        *               */
0x00, 0x00, 0x00, /* *        *                     */

/* Character (0x61): bbw=4, bbh=5, bbx=1, bby=0, width=4 */
0x00, 0xe8, 0xa8, 0x70, /*            * ***   * * *    ***  */
0x00, 0x00, 0x00, 0x00, /*            * ***   * * *    ***          */

/* Character (0x62): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0xfe, 0x88, 0x88, 0x70, /*          *******   *   *   *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *******   *   *   *   *    ***            */

/* Character (0x63): bbw=3, bbh=5, bbx=1, bby=0, width=4 */
0x00, 0x70, 0x88, 0x88, /*             ***    *   *   *   * */
0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *   *         */

/* Character (0x64): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x88, 0xfe, /*             ***    *   *   *   * ******* */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *   * *******           */

/* Character (0x65): bbw=3, bbh=5, bbx=1, bby=0, width=4 */
0x00, 0x70, 0xa8, 0xb0, /*             ***    * * *    ** * */
0x00, 0x00, 0x00, 0x00, /*             ***    * * *    ** *         */

/* Character (0x66): bbw=3, bbh=7, bbx=1, bby=0, width=3 */
0x00, 0x08, 0xfc, /*            *      ****** */
0x00, 0x00, 0x00, /*            *      ******       */

/* Character (0x67): bbw=4, bbh=6, bbx=1, bby=-1, width=5 */
0x00, 0x30, 0x48, 0x48, 0xf8, /*             **     *  *    *  *    ***** */
0x00, 0x00, 0x01, 0x01, 0x00, /*             **     *  *    *  *    *****    * *    */

/* Character (0x68): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0xfe, 0x08, 0x08, 0xf0, /*          *******   *       *        **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *******   *       *        ****           */

/* Character (0x69): bbw=1, bbh=7, bbx=1, bby=0, width=2 */
0x00, 0xfa, /*          * ***** */
0x00, 0x00, /*          * *****     */

/* Character (0x6a): bbw=2, bbh=9, bbx=0, bby=-2, width=2 */
0x00, 0xfa, /*          * ***** */
0x02, 0x01, /*          * ***** **  */

/* Character (0x6b): bbw=3, bbh=7, bbx=1, bby=0, width=4 */
0x00, 0xfe, 0x30, 0xc8, /*          *******    **     *  ** */
0x00, 0x00, 0x00, 0x00, /*          *******    **     *  **         */

/* Character (0x6c): bbw=1, bbh=7, bbx=1, bby=0, width=2 */
0x00, 0xfe, /*          ******* */
0x00, 0x00, /*          *******     */

/* Character (0x6d): bbw=5, bbh=5, bbx=1, bby=0, width=6 */
0x00, 0xf8, 0x08, 0xf8, 0x08, 0xf0, /*            *****   *       *****   *        **** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            *****   *       *****   *        ****             */

/* Character (0x6e): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x08, 0x08, 0xf0, /*            *****   *       *        **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *****   *       *        ****           */

/* Character (0x6f): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x88, 0x70, /*             ***    *   *   *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *   *    ***            */

/* Character (0x70): bbw=4, bbh=6, bbx=1, bby=-1, width=5 */
0x00, 0xf8, 0x88, 0x88, 0x70, /*            *****   *   *   *   *    ***  */
0x00, 0x01, 0x00, 0x00, 0x00, /*            *****   *   *   *   *    ***   *        */

/* Character (0x71): bbw=4, bbh=6, bbx=1, bby=-1, width=5 */
0x00, 0x70, 0x88, 0x88, 0xf8, /*             ***    *   *   *   *   ***** */
0x00, 0x00, 0x00, 0x00, 0x01, /*             ***    *   *   *   *   *****        *  */

/* Character (0x72): bbw=3, bbh=5, bbx=1, bby=0, width=3 */
0x00, 0xf8, 0x10, /*            *****    *    */
0x00, 0x00, 0x00, /*            *****    *          */

/* Character (0x73): bbw=3, bbh=5, bbx=1, bby=0, width=4 */
0x00, 0x90, 0xa8, 0x68, /*             *  *   * * *   * **  */
0x00, 0x00, 0x00, 0x00, /*             *  *   * * *   * **          */

/* Character (0x74): bbw=3, bbh=7, bbx=1, bby=0, width=3 */
0x00, 0x08, 0xfe, /*            *     ******* */
0x00, 0x00, 0x00, /*            *     *******       */

/* Character (0x75): bbw=3, bbh=5, bbx=1, bby=0, width=4 */
0x00, 0x78, 0x80, 0xf8, /*            ****        *   ***** */
0x00, 0x00, 0x00, 0x00, /*            ****        *   *****         */

/* Character (0x76): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x80, 0x40, 0x38, /*            ****        *      *    ***   */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****        *      *    ***             */

/* Character (0x77): bbw=5, bbh=5, bbx=1, bby=0, width=6 */
0x00, 0x38, 0xc0, 0x38, 0xc0, 0x38, /*            ***        **   ***        **   ***   */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            ***        **   ***        **   ***               */

/* Character (0x78): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xd8, 0x20, 0x20, 0xd8, /*            ** **     *       *     ** ** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ** **     *       *     ** **           */

/* Character (0x79): bbw=4, bbh=6, bbx=1, bby=-1, width=4 */
0x00, 0x38, 0xc0, 0x40, /*            ***        **      *  */
0x00, 0x01, 0x00, 0x00, /*            ***        **      *   *      */

/* Character (0x7a): bbw=3, bbh=5, bbx=1, bby=0, width=4 */
0x00, 0xc8, 0xa8, 0x98, /*            *  **   * * *   **  * */
0x00, 0x00, 0x00, 0x00, /*            *  **   * * *   **  *         */

/* Character (0x7b): bbw=3, bbh=7, bbx=0, bby=-1, width=2 */
0x20, 0xf8, /*      *     ***** */
0x00, 0x00, /*      *     *****     */

/* Character (0x7c): bbw=1, bbh=7, bbx=1, bby=-1, width=2 */
0x00, 0xfc, /*           ****** */
0x00, 0x01, /*           ******  *  */

/* Character (0x7d): bbw=3, bbh=7, bbx=0, bby=-1, width=2 */
0x04, 0xf8, /*   *        ***** */
0x01, 0x00, /*   *        ******    */

/* Character (0x7e): bbw=5, bbh=2, bbx=1, bby=2, width=6 */
0x00, 0x20, 0x10, 0x20, 0x20, 0x10, /*              *      *        *       *      *    */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*              *      *        *       *      *                */

/* Character (0xa0): bbw=1, bbh=1, bbx=0, bby=0, width=2 */
0x00, 0x00, /*                  */
0x00, 0x00, /*                      */

/* Character (0xa1): bbw=5, bbh=8, bbx=1, bby=-2, width=6 */
0x00, 0xc0, 0x30, 0x2c, 0x30, 0xc0, /*               **    **    ** *      **        ** */
0x00, 0x00, 0x00, 0x03, 0x02, 0x00, /*               **    **    ** *      **        **      ** *   */

/* Character (0xa2): bbw=4, bbh=2, bbx=0, bby=6, width=4 */
0x01, 0x02, 0x02, 0x01, /* *        *       *      *        */
0x00, 0x00, 0x00, 0x00, /* *        *       *      *                */

/* Character (0xa3): bbw=5, bbh=8, bbx=0, bby=0, width=6 */
0x10, 0xff, 0x88, 0x80, 0x80, 0x00, /*     *   ********   *   *       *       *         */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*     *   ********   *   *       *       *                     */

/* Character (0xa4): bbw=5, bbh=5, bbx=0, bby=0, width=4 */
0x88, 0x70, 0x50, 0x70, /*    *   *    ***     * *     ***  */
0x00, 0x00, 0x00, 0x00, /*    *   *    ***     * *     ***          */

/* Character (0xa5): bbw=5, bbh=6, bbx=2, bby=0, width=7 */
0x00, 0x00, 0xfc, 0x80, 0x80, 0x00, 0x1c, /*                   ******       *       *          ***    */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   ******       *       *          ***                  */

/* Character (0xa6): bbw=4, bbh=9, bbx=2, bby=0, width=6 */
0x00, 0x00, 0x98, 0x95, 0x94, 0x64, /*                    **  ** * *  *  * *  *  *  **  */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*                    **  ** * *  *  * *  *  *  **          *   */

/* Character (0xa7): bbw=4, bbh=8, bbx=1, bby=-2, width=5 */
0x00, 0x28, 0x54, 0xd4, 0xa4, /*            * *    * * *   * * **  *  * * */
0x00, 0x02, 0x02, 0x02, 0x01, /*            * *    * * *   * * **  *  * *   * * **  */

/* Character (0xa8): bbw=4, bbh=1, bbx=0, bby=5, width=2 */
0x04, 0x00, /*   *              */
0x00, 0x00, /*   *                  */

/* Character (0xa9): bbw=5, bbh=9, bbx=1, bby=0, width=7 */
0x00, 0x48, 0x94, 0x95, 0x94, 0x74, 0x00, /*            *  *   * *  ** * *  *  * *  *  * ***          */
0x00, 0x00, 0x02, 0x00, 0x02, 0x00, 0x00, /*            *  *   * *  ** * *  *  * *  *  * ***              *   *     */

/* Character (0xaa): bbw=4, bbh=8, bbx=2, bby=-2, width=6 */
0x00, 0x00, 0x98, 0x94, 0x94, 0x64, /*                    **  *  * *  *  * *  *  *  **  */
0x00, 0x00, 0x00, 0x02, 0x01, 0x00, /*                    **  *  * *  *  * *  *  *  **        **    */

/* Character (0xab): bbw=3, bbh=9, bbx=1, bby=0, width=4 */
0x00, 0x04, 0xfd, 0x04, /*           *     * ******  *      */
0x00, 0x02, 0x00, 0x02, /*           *     * ******  *        *   * */

/* Character (0xac): bbw=4, bbh=9, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xc4, 0xa4, 0x95, 0x8c, /*                   *   **  *  * ** * *  *  **   * */
0x00, 0x00, 0x00, 0x00, 0x00, 0x02, /*                   *   **  *  * ** * *  *  **   *           * */

/* Character (0xad): bbw=2, bbh=1, bbx=0, bby=2, width=3 */
0x20, 0x20, 0x00, /*      *       *           */
0x00, 0x00, 0x00, /*      *       *                 */

/* Character (0xae): bbw=5, bbh=9, bbx=1, bby=0, width=7 */
0x00, 0xc4, 0xa4, 0x95, 0x8c, 0x84, 0x00, /*           *   **  *  * ** * *  *  **   *  *    *         */
0x00, 0x00, 0x02, 0x00, 0x02, 0x00, 0x00, /*           *   **  *  * ** * *  *  **   *  *    *             *   *     */

/* Character (0xaf): bbw=4, bbh=8, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xc4, 0xa4, 0x95, 0x8c, /*                   *   **  *  * ** * *  *  **   * */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                   *   **  *  * ** * *  *  **   *             */

/* Character (0xb0): bbw=3, bbh=3, bbx=1, bby=3, width=3 */
0x00, 0x08, 0x14, /*            *      * *    */
0x00, 0x00, 0x00, /*            *      * *          */

/* Character (0xb1): bbw=4, bbh=7, bbx=1, bby=-2, width=4 */
0x00, 0xe8, 0xa8, 0x70, /*            * ***   * * *    ***  */
0x00, 0x00, 0x03, 0x02, /*            * ***   * * *    ***     ** * */

/* Character (0xb2): bbw=2, bbh=2, bbx=1, bby=-2, width=3 */
0x00, 0x00, 0x00, /*                          */
0x00, 0x03, 0x02, /*                           ** * */

/* Character (0xb3): bbw=3, bbh=8, bbx=0, bby=0, width=3 */
0x10, 0xff, 0x08, /*     *   ********   *     */
0x00, 0x00, 0x00, /*     *   ********   *           */

/* Character (0xb4): bbw=2, bbh=2, bbx=0, bby=4, width=2 */
0x08, 0x04, /*    *      *      */
0x00, 0x00, /*    *      *          */

/* Character (0xb5): bbw=3, bbh=7, bbx=1, bby=0, width=4 */
0x00, 0xfe, 0x00, 0x1c, /*          *******          ***    */
0x00, 0x00, 0x00, 0x00, /*          *******          ***            */

/* Character (0xb6): bbw=3, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0x90, 0xaa, 0x69, /*             *  * * * * **  * **  */
0x00, 0x00, 0x00, 0x00, /*             *  * * * * **  * **          */

/* Character (0xb7): bbw=3, bbh=2, bbx=0, bby=6, width=3 */
0x01, 0x02, 0x01, /* *        *      *        */
0x00, 0x00, 0x00, /* *        *      *              */

/* Character (0xb8): bbw=2, bbh=2, bbx=0, bby=-2, width=2 */
0x00, 0x00, /*                  */
0x02, 0x01, /*                  **  */

/* Character (0xb9): bbw=4, bbh=9, bbx=0, bby=0, width=5 */
0x48, 0x95, 0x94, 0x68, 0x00, /*    *  * * * *  *  * *  *   * **          */
0x02, 0x00, 0x02, 0x00, 0x00, /*    *  * * * *  *  * *  *   * **          *   *     */

/* Character (0xba): bbw=3, bbh=7, bbx=1, bby=-2, width=4 */
0x00, 0x90, 0xa8, 0x68, /*             *  *   * * *   * **  */
0x00, 0x02, 0x01, 0x00, /*             *  *   * * *   * **    **    */

/* Character (0xbb): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x08, 0xfe, 0x08, 0x1c, /*            *     *******   *      ***    */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *     *******   *      ***              */

/* Character (0xbc): bbw=3, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0xc8, 0xaa, 0x99, /*            *  ** * * * **  **  * */
0x00, 0x00, 0x00, 0x00, /*            *  ** * * * **  **  *         */

/* Character (0xbd): bbw=5, bbh=2, bbx=0, bby=6, width=5 */
0x02, 0x01, 0x00, 0x02, 0x01, /*  *      *                *      *        */
0x00, 0x00, 0x00, 0x00, 0x00, /*  *      *                *      *                  */

/* Character (0xbe): bbw=4, bbh=9, bbx=0, bby=0, width=5 */
0xc4, 0xa5, 0x94, 0x8c, 0x00, /*   *   *** *  * *  * *  *  **   *         */
0x02, 0x00, 0x02, 0x00, 0x00, /*   *   *** *  * *  * *  *  **   *         *   *     */

/* Character (0xbf): bbw=3, bbh=7, bbx=1, bby=0, width=4 */
0x00, 0xc8, 0xaa, 0x98, /*            *  ** * * * *   **  * */
0x00, 0x00, 0x00, 0x00, /*            *  ** * * * *   **  *         */

/* Character (0xc0): bbw=4, bbh=9, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x25, 0x24, 0xd8, /*                   ******* *  *    *  *     ** ** */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*                   ******* *  *    *  *     ** **         *   */

/* Character (0xc1): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0xc0, 0x30, 0x2d, 0x30, 0xc0, /*               **    **  * ** *      **        ** */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*               **    **  * ** *      **        **         *   */

/* Character (0xc2): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0xc0, 0x31, 0x2c, 0x31, 0xc0, /*               ***   **    ** *  *   **        ** */
0x00, 0x00, 0x00, 0x02, 0x00, 0x00, /*               ***   **    ** *  *   **        **       *     */

/* Character (0xc3): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0xc0, 0x30, 0x2d, 0x31, 0xc0, /*               **    **  * ** *  *   **        ** */
0x00, 0x00, 0x02, 0x00, 0x00, 0x02, /*               **    **  * ** *  *   **        **     *     * */

/* Character (0xc4): bbw=5, bbh=8, bbx=1, bby=0, width=6 */
0x00, 0xc0, 0x31, 0x2c, 0x31, 0xc0, /*               ***   **    ** *  *   **        ** */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*               ***   **    ** *  *   **        **             */

/* Character (0xc5): bbw=3, bbh=9, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xfd, 0x80, 0x80, /*                 * ******       *       * */
0x00, 0x00, 0x00, 0x02, 0x00, /*                 * ******       *       *       *   */

/* Character (0xc6): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x84, 0x85, 0x84, 0x48, /*            ****   *    ** *    *  *    *   *  *  */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*            ****   *    ** *    *  *    *   *  *          *   */

/* Character (0xc7): bbw=5, bbh=8, bbx=1, bby=-2, width=6 */
0x00, 0x78, 0x84, 0x84, 0x84, 0x58, /*            ****   *    *  *    *  *    *   ** *  */
0x00, 0x02, 0x01, 0x00, 0x00, 0x00, /*            ****   *    *  *    *  *    *   ** *    **        */

/* Character (0xc8): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x84, 0x85, 0x84, 0x48, /*            ****   *    ** *    *  *    *   *  *  */
0x00, 0x00, 0x02, 0x00, 0x02, 0x00, /*            ****   *    ** *    *  *    *   *  *      *   *   */

/* Character (0xc9): bbw=4, bbh=9, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x95, 0x94, 0x84, /*                   ******* * *  *  * *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*                   ******* * *  *  * *  *  *    *         *   */

/* Character (0xca): bbw=4, bbh=8, bbx=2, bby=-2, width=6 */
0x00, 0x00, 0xfc, 0x94, 0x94, 0x84, /*                   ******  * *  *  * *  *  *    * */
0x00, 0x00, 0x00, 0x03, 0x02, 0x00, /*                   ******  * *  *  * *  *  *    *      ** *   */

/* Character (0xcb): bbw=4, bbh=8, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfd, 0x94, 0x95, 0x84, /*                 * ******  * *  ** * *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*                 * ******  * *  ** * *  *  *    *             */

/* Character (0xcc): bbw=4, bbh=9, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x95, 0x94, 0x84, /*                   ******* * *  *  * *  *  *    * */
0x00, 0x00, 0x02, 0x00, 0x02, 0x00, /*                   ******* * *  *  * *  *  *    *     *   *   */

/* Character (0xcd): bbw=2, bbh=9, bbx=1, bby=0, width=2 */
0x00, 0xfd, /*         * ****** */
0x00, 0x00, /*         * ******     */

/* Character (0xce): bbw=3, bbh=9, bbx=0, bby=0, width=2 */
0x01, 0xfc, /* *         ****** */
0x00, 0x02, /* *         ******   * */

/* Character (0xcf): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0xfc, 0x84, 0x85, 0x84, 0x78, /*           ******  *    ** *    *  *    *   ****  */
0x00, 0x00, 0x02, 0x00, 0x02, 0x00, /*           ******  *    ** *    *  *    *   ****      *   *   */

/* Character (0xd0): bbw=5, bbh=6, bbx=1, bby=0, width=6 */
0x00, 0x10, 0xfc, 0x94, 0x84, 0x78, /*             *     ******  * *  *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*             *     ******  * *  *  *    *   ****              */

/* Character (0xd1): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0xfc, 0x08, 0x31, 0x40, 0xfc, /*           ******   *    *   **        *   ****** */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*           ******   *    *   **        *   ******         *   */

/* Character (0xd2): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0xfc, 0x08, 0x31, 0x40, 0xfc, /*           ******   *    *   **        *   ****** */
0x00, 0x00, 0x02, 0x00, 0x02, 0x00, /*           ******   *    *   **        *   ******     *   *   */

/* Character (0xd3): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x84, 0x85, 0x84, 0x78, /*            ****   *    ** *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*            ****   *    ** *    *  *    *   ****          *   */

/* Character (0xd4): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x85, 0x84, 0x85, 0x78, /*            **** * *    *  *    ** *    *   ****  */
0x00, 0x00, 0x00, 0x02, 0x00, 0x00, /*            **** * *    *  *    ** *    *   ****        *     */

/* Character (0xd5): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x79, 0x84, 0x84, 0x85, 0x78, /*         *  ****   *    *  *    ** *    *   ****  */
0x00, 0x00, 0x02, 0x00, 0x00, 0x02, /*         *  ****   *    *  *    ** *    *   ****      *     * */

/* Character (0xd6): bbw=5, bbh=8, bbx=1, bby=0, width=6 */
0x00, 0x78, 0x85, 0x84, 0x85, 0x78, /*            **** * *    *  *    ** *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*            **** * *    *  *    ** *    *   ****              */

/* Character (0xd7): bbw=4, bbh=4, bbx=1, bby=0, width=5 */
0x00, 0x90, 0x60, 0x60, 0x90, /*             *  *     **      **     *  * */
0x00, 0x00, 0x00, 0x00, 0x00, /*             *  *     **      **     *  *           */

/* Character (0xd8): bbw=4, bbh=9, bbx=2, bby=0, width=6 */
0x00, 0x00, 0xfc, 0x25, 0x24, 0xd8, /*                   ******* *  *    *  *     ** ** */
0x00, 0x00, 0x02, 0x00, 0x02, 0x00, /*                   ******* *  *    *  *     ** **     *   *   */

/* Character (0xd9): bbw=5, bbh=10, bbx=1, bby=0, width=6 */
0x00, 0x7c, 0x80, 0x81, 0x80, 0x7c, /*           *****        **      *       *  *****  */
0x00, 0x00, 0x02, 0x01, 0x02, 0x00, /*           *****        **      *       *  *****      **  *   */

/* Character (0xda): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x7c, 0x80, 0x81, 0x80, 0x7c, /*           *****        **      *       *  *****  */
0x00, 0x00, 0x00, 0x00, 0x02, 0x00, /*           *****        **      *       *  *****          *   */

/* Character (0xdb): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x7d, 0x80, 0x80, 0x81, 0x7c, /*         * *****        *       **      *  *****  */
0x00, 0x00, 0x02, 0x00, 0x00, 0x02, /*         * *****        *       **      *  *****      *     * */

/* Character (0xdc): bbw=5, bbh=8, bbx=1, bby=0, width=6 */
0x00, 0x7c, 0x81, 0x80, 0x81, 0x7c, /*           ***** *      *       **      *  *****  */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*           ***** *      *       **      *  *****              */

/* Character (0xdd): bbw=5, bbh=9, bbx=1, bby=0, width=6 */
0x00, 0x04, 0x1c, 0xe0, 0x21, 0x1c, /*           *       ***        ****    *    ***    */
0x00, 0x00, 0x00, 0x00, 0x00, 0x02, /*           *       ***        ****    *    ***              * */

/* Character (0xde): bbw=3, bbh=8, bbx=1, bby=-2, width=4 */
0x00, 0x04, 0xfc, 0x04, /*           *       ******  *      */
0x00, 0x02, 0x01, 0x00, /*           *       ******  *        **    */

/* Character (0xdf): bbw=4, bbh=7, bbx=2, bby=-1, width=6 */
0x00, 0x00, 0xf8, 0x04, 0x94, 0x68, /*                    *****  *       * *  *   * **  */
0x00, 0x00, 0x01, 0x00, 0x00, 0x00, /*                    *****  *       * *  *   * **     *        */

/* Character (0xe0): bbw=3, bbh=8, bbx=1, bby=0, width=3 */
0x00, 0xf8, 0x12, /*            ***** *  *    */
0x00, 0x00, 0x00, /*            ***** *  *          */

/* Character (0xe1): bbw=4, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0xe8, 0xaa, 0x71, /*            * *** * * * **   ***  */
0x00, 0x00, 0x00, 0x00, /*            * *** * * * **   ***          */

/* Character (0xe2): bbw=4, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0xea, 0xa9, 0x72, /*          * * ****  * * * *  ***  */
0x00, 0x00, 0x00, 0x00, /*          * * ****  * * * *  ***          */

/* Character (0xe3): bbw=4, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0xe9, 0xaa, 0x72, /*         *  * *** * * * * *  ***  */
0x00, 0x00, 0x00, 0x00, /*         *  * *** * * * * *  ***          */

/* Character (0xe4): bbw=4, bbh=7, bbx=1, bby=0, width=4 */
0x00, 0xea, 0xa8, 0x72, /*          * * ***   * * * *  ***  */
0x00, 0x00, 0x00, 0x00, /*          * * ***   * * * *  ***          */

/* Character (0xe5): bbw=2, bbh=10, bbx=1, bby=0, width=2 */
0x00, 0xfe, /*          ******* */
0x00, 0x02, /*          *******   * */

/* Character (0xe6): bbw=3, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0x70, 0x8a, 0x89, /*             ***  * *   **  *   * */
0x00, 0x00, 0x00, 0x00, /*             ***  * *   **  *   *         */

/* Character (0xe7): bbw=3, bbh=7, bbx=1, bby=-2, width=4 */
0x00, 0x70, 0x88, 0x88, /*             ***    *   *   *   * */
0x00, 0x02, 0x01, 0x00, /*             ***    *   *   *   *   **    */

/* Character (0xe8): bbw=3, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0x71, 0x8a, 0x89, /*         *   ***  * *   **  *   * */
0x00, 0x00, 0x00, 0x00, /*         *   ***  * *   **  *   *         */

/* Character (0xe9): bbw=3, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0x70, 0xaa, 0xb1, /*             ***  * * * **   ** * */
0x00, 0x00, 0x00, 0x00, /*             ***  * * * **   ** *         */

/* Character (0xea): bbw=3, bbh=7, bbx=1, bby=-2, width=4 */
0x00, 0x70, 0xa8, 0xb0, /*             ***    * * *    ** * */
0x00, 0x00, 0x03, 0x02, /*             ***    * * *    ** *    ** * */

/* Character (0xeb): bbw=3, bbh=7, bbx=1, bby=0, width=4 */
0x00, 0x72, 0xa8, 0xb2, /*          *  ***    * * * *  ** * */
0x00, 0x00, 0x00, 0x00, /*          *  ***    * * * *  ** *         */

/* Character (0xec): bbw=3, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0x71, 0xaa, 0xb1, /*         *   ***  * * * **   ** * */
0x00, 0x00, 0x00, 0x00, /*         *   ***  * * * **   ** *         */

/* Character (0xed): bbw=2, bbh=8, bbx=1, bby=0, width=2 */
0x00, 0xfa, /*          * ***** */
0x00, 0x00, /*          * *****     */

/* Character (0xee): bbw=3, bbh=8, bbx=0, bby=0, width=2 */
0x02, 0xf9, /*  *      *  ***** */
0x00, 0x00, /*  *      *  *****     */

/* Character (0xef): bbw=6, bbh=7, bbx=1, bby=0, width=7 */
0x00, 0x70, 0x88, 0x88, 0xfe, 0x00, 0x1c, /*             ***    *   *   *   * *******          ***    */
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *   * *******          ***                  */

/* Character (0xf0): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x8c, 0x8c, 0xfe, /*             ***   **   *  **   * ******* */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***   **   *  **   * *******           */

/* Character (0xf1): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x0a, 0x09, 0xf0, /*            ***** * *    *  *        **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ***** * *    *  *        ****           */

/* Character (0xf2): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xf9, 0x0a, 0x09, 0xf0, /*         *  ***** * *    *  *        **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*         *  ***** * *    *  *        ****           */

/* Character (0xf3): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x8a, 0x71, /*             ***    *   * * *   **   ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   * * *   **   ***            */

/* Character (0xf4): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x8a, 0x70, /*          *  *** *  *   * * *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   * * *   *    ***            */

/* Character (0xf5): bbw=5, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x88, 0x72, /*          *  *** *  *   *   *   * *  ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   *   *   * *  ***            */

/* Character (0xf6): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x88, 0x88, 0x72, /*          *  ***    *   *   *   * *  ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  ***    *   *   *   * *  ***            */

/* Character (0xf7): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x20, 0x20, 0xa8, 0x20, /*              *       *     * * *     *   */
0x00, 0x00, 0x00, 0x00, 0x00, /*              *       *     * * *     *             */

/* Character (0xf8): bbw=3, bbh=8, bbx=1, bby=0, width=3 */
0x00, 0xf9, 0x12, /*         *  ***** *  *    */
0x00, 0x00, 0x00, /*         *  ***** *  *          */

/* Character (0xf9): bbw=3, bbh=9, bbx=1, bby=0, width=4 */
0x00, 0x79, 0x82, 0xf9, /*         *  ****  *     **  ***** */
0x00, 0x00, 0x02, 0x00, /*         *  ****  *     **  *****     *   */

/* Character (0xfa): bbw=3, bbh=8, bbx=1, bby=0, width=4 */
0x00, 0x78, 0x82, 0xf9, /*            ****  *     **  ***** */
0x00, 0x00, 0x00, 0x00, /*            ****  *     **  *****         */

/* Character (0xfb): bbw=5, bbh=8, bbx=0, bby=0, width=4 */
0x02, 0x79, 0x80, 0xfa, /*  *      *  ****        * * ***** */
0x00, 0x00, 0x00, 0x00, /*  *      *  ****        * * *****         */

/* Character (0xfc): bbw=3, bbh=7, bbx=1, bby=0, width=4 */
0x00, 0x7a, 0x80, 0xfa, /*          * ****        * * ***** */
0x00, 0x00, 0x00, 0x00, /*          * ****        * * *****         */

/* Character (0xfd): bbw=4, bbh=9, bbx=1, bby=-1, width=4 */
0x00, 0x38, 0xc0, 0x42, /*            ***        ** *    *  */
0x00, 0x01, 0x00, 0x00, /*            ***        ** *    *   *      */

/* Character (0xfe): bbw=3, bbh=9, bbx=1, bby=-2, width=3 */
0x00, 0x08, 0xfe, /*            *     ******* */
0x00, 0x02, 0x01, /*            *     *******   **  */

/* Character (0xff): bbw=1, bbh=1, bbx=1, bby=7, width=3 */
0x00, 0x01, 0x00, /*         *                */
0x00, 0x00, 0x00, /*         *                      */
};

/* Character->glyph data. */
static const PROGMEM uint16_t helvR8_offset[] = {
  0,	/* (0x00) */
  0,	/* (0x01) */
  0,	/* (0x02) */
  0,	/* (0x03) */
  0,	/* (0x04) */
  0,	/* (0x05) */
  0,	/* (0x06) */
  0,	/* (0x07) */
  0,	/* (0x08) */
  0,	/* (0x09) */
  0,	/* (0x0a) */
  0,	/* (0x0b) */
  0,	/* (0x0c) */
  0,	/* (0x0d) */
  0,	/* (0x0e) */
  0,	/* (0x0f) */
  0,	/* (0x10) */
  0,	/* (0x11) */
  0,	/* (0x12) */
  0,	/* (0x13) */
  0,	/* (0x14) */
  0,	/* (0x15) */
  0,	/* (0x16) */
  0,	/* (0x17) */
  0,	/* (0x18) */
  0,	/* (0x19) */
  0,	/* (0x1a) */
  0,	/* (0x1b) */
  0,	/* (0x1c) */
  0,	/* (0x1d) */
  0,	/* (0x1e) */
  0,	/* (0x1f) */
  12,	/* (0x20) */
  16,	/* (0x21) */
  20,	/* (0x22) */
  26,	/* (0x23) */
  36,	/* (0x24) */
  46,	/* (0x25) */
  60,	/* (0x26) */
  72,	/* (0x27) */
  76,	/* (0x28) */
  82,	/* (0x29) */
  88,	/* (0x2a) */
  94,	/* (0x2b) */
  104,	/* (0x2c) */
  108,	/* (0x2d) */
  114,	/* (0x2e) */
  118,	/* (0x2f) */
  122,	/* (0x30) */
  132,	/* (0x31) */
  142,	/* (0x32) */
  152,	/* (0x33) */
  162,	/* (0x34) */
  172,	/* (0x35) */
  182,	/* (0x36) */
  192,	/* (0x37) */
  202,	/* (0x38) */
  212,	/* (0x39) */
  222,	/* (0x3a) */
  226,	/* (0x3b) */
  230,	/* (0x3c) */
  240,	/* (0x3d) */
  248,	/* (0x3e) */
  258,	/* (0x3f) */
  268,	/* (0x40) */
  286,	/* (0x41) */
  298,	/* (0x42) */
  310,	/* (0x43) */
  322,	/* (0x44) */
  334,	/* (0x45) */
  346,	/* (0x46) */
  356,	/* (0x47) */
  368,	/* (0x48) */
  380,	/* (0x49) */
  384,	/* (0x4a) */
  392,	/* (0x4b) */
  404,	/* (0x4c) */
  414,	/* (0x4d) */
  428,	/* (0x4e) */
  440,	/* (0x4f) */
  452,	/* (0x50) */
  464,	/* (0x51) */
  476,	/* (0x52) */
  488,	/* (0x53) */
  500,	/* (0x54) */
  508,	/* (0x55) */
  520,	/* (0x56) */
  532,	/* (0x57) */
  546,	/* (0x58) */
  558,	/* (0x59) */
  570,	/* (0x5a) */
  582,	/* (0x5b) */
  586,	/* (0x5c) */
  590,	/* (0x5d) */
  594,	/* (0x5e) */
  604,	/* (0x5f) */
  614,	/* (0x60) */
  620,	/* (0x61) */
  628,	/* (0x62) */
  638,	/* (0x63) */
  646,	/* (0x64) */
  656,	/* (0x65) */
  664,	/* (0x66) */
  670,	/* (0x67) */
  680,	/* (0x68) */
  690,	/* (0x69) */
  694,	/* (0x6a) */
  698,	/* (0x6b) */
  706,	/* (0x6c) */
  710,	/* (0x6d) */
  722,	/* (0x6e) */
  732,	/* (0x6f) */
  742,	/* (0x70) */
  752,	/* (0x71) */
  762,	/* (0x72) */
  768,	/* (0x73) */
  776,	/* (0x74) */
  782,	/* (0x75) */
  790,	/* (0x76) */
  800,	/* (0x77) */
  812,	/* (0x78) */
  822,	/* (0x79) */
  830,	/* (0x7a) */
  838,	/* (0x7b) */
  842,	/* (0x7c) */
  846,	/* (0x7d) */
  850,	/* (0x7e) */
  0,	/* (0x7f) */
  0,	/* (0x80) */
  0,	/* (0x81) */
  0,	/* (0x82) */
  0,	/* (0x83) */
  0,	/* (0x84) */
  0,	/* (0x85) */
  0,	/* (0x86) */
  0,	/* (0x87) */
  0,	/* (0x88) */
  0,	/* (0x89) */
  0,	/* (0x8a) */
  0,	/* (0x8b) */
  0,	/* (0x8c) */
  0,	/* (0x8d) */
  0,	/* (0x8e) */
  0,	/* (0x8f) */
  0,	/* (0x90) */
  0,	/* (0x91) */
  0,	/* (0x92) */
  0,	/* (0x93) */
  0,	/* (0x94) */
  0,	/* (0x95) */
  0,	/* (0x96) */
  0,	/* (0x97) */
  0,	/* (0x98) */
  0,	/* (0x99) */
  0,	/* (0x9a) */
  0,	/* (0x9b) */
  0,	/* (0x9c) */
  0,	/* (0x9d) */
  0,	/* (0x9e) */
  0,	/* (0x9f) */
  862,	/* (0xa0) */
  866,	/* (0xa1) */
  878,	/* (0xa2) */
  886,	/* (0xa3) */
  898,	/* (0xa4) */
  906,	/* (0xa5) */
  920,	/* (0xa6) */
  932,	/* (0xa7) */
  942,	/* (0xa8) */
  946,	/* (0xa9) */
  960,	/* (0xaa) */
  972,	/* (0xab) */
  980,	/* (0xac) */
  992,	/* (0xad) */
  998,	/* (0xae) */
  1012,	/* (0xaf) */
  1024,	/* (0xb0) */
  1030,	/* (0xb1) */
  1038,	/* (0xb2) */
  1044,	/* (0xb3) */
  1050,	/* (0xb4) */
  1054,	/* (0xb5) */
  1062,	/* (0xb6) */
  1070,	/* (0xb7) */
  1076,	/* (0xb8) */
  1080,	/* (0xb9) */
  1090,	/* (0xba) */
  1098,	/* (0xbb) */
  1108,	/* (0xbc) */
  1116,	/* (0xbd) */
  1126,	/* (0xbe) */
  1136,	/* (0xbf) */
  1144,	/* (0xc0) */
  1156,	/* (0xc1) */
  1168,	/* (0xc2) */
  1180,	/* (0xc3) */
  1192,	/* (0xc4) */
  1204,	/* (0xc5) */
  1214,	/* (0xc6) */
  1226,	/* (0xc7) */
  1238,	/* (0xc8) */
  1250,	/* (0xc9) */
  1262,	/* (0xca) */
  1274,	/* (0xcb) */
  1286,	/* (0xcc) */
  1298,	/* (0xcd) */
  1302,	/* (0xce) */
  1306,	/* (0xcf) */
  1318,	/* (0xd0) */
  1330,	/* (0xd1) */
  1342,	/* (0xd2) */
  1354,	/* (0xd3) */
  1366,	/* (0xd4) */
  1378,	/* (0xd5) */
  1390,	/* (0xd6) */
  1402,	/* (0xd7) */
  1412,	/* (0xd8) */
  1424,	/* (0xd9) */
  1436,	/* (0xda) */
  1448,	/* (0xdb) */
  1460,	/* (0xdc) */
  1472,	/* (0xdd) */
  1484,	/* (0xde) */
  1492,	/* (0xdf) */
  1504,	/* (0xe0) */
  1510,	/* (0xe1) */
  1518,	/* (0xe2) */
  1526,	/* (0xe3) */
  1534,	/* (0xe4) */
  1542,	/* (0xe5) */
  1546,	/* (0xe6) */
  1554,	/* (0xe7) */
  1562,	/* (0xe8) */
  1570,	/* (0xe9) */
  1578,	/* (0xea) */
  1586,	/* (0xeb) */
  1594,	/* (0xec) */
  1602,	/* (0xed) */
  1606,	/* (0xee) */
  1610,	/* (0xef) */
  1624,	/* (0xf0) */
  1634,	/* (0xf1) */
  1644,	/* (0xf2) */
  1654,	/* (0xf3) */
  1664,	/* (0xf4) */
  1674,	/* (0xf5) */
  1684,	/* (0xf6) */
  1694,	/* (0xf7) */
  1704,	/* (0xf8) */
  1710,	/* (0xf9) */
  1718,	/* (0xfa) */
  1726,	/* (0xfb) */
  1734,	/* (0xfc) */
  1742,	/* (0xfd) */
  1750,	/* (0xfe) */
  1756,	/* (0xff) */
};

/* Character width data. */
static const PROGMEM uint8_t helvR8_width[] = {
  6,	/* (0x00) */
  6,	/* (0x01) */
  6,	/* (0x02) */
  6,	/* (0x03) */
  6,	/* (0x04) */
  6,	/* (0x05) */
  6,	/* (0x06) */
  6,	/* (0x07) */
  6,	/* (0x08) */
  6,	/* (0x09) */
  6,	/* (0x0a) */
  6,	/* (0x0b) */
  6,	/* (0x0c) */
  6,	/* (0x0d) */
  6,	/* (0x0e) */
  6,	/* (0x0f) */
  6,	/* (0x10) */
  6,	/* (0x11) */
  6,	/* (0x12) */
  6,	/* (0x13) */
  6,	/* (0x14) */
  6,	/* (0x15) */
  6,	/* (0x16) */
  6,	/* (0x17) */
  6,	/* (0x18) */
  6,	/* (0x19) */
  6,	/* (0x1a) */
  6,	/* (0x1b) */
  6,	/* (0x1c) */
  6,	/* (0x1d) */
  6,	/* (0x1e) */
  6,	/* (0x1f) */
  2,	/* (0x20) */
  2,	/* (0x21) */
  3,	/* (0x22) */
  5,	/* (0x23) */
  5,	/* (0x24) */
  7,	/* (0x25) */
  6,	/* (0x26) */
  2,	/* (0x27) */
  3,	/* (0x28) */
  3,	/* (0x29) */
  3,	/* (0x2a) */
  5,	/* (0x2b) */
  2,	/* (0x2c) */
  3,	/* (0x2d) */
  2,	/* (0x2e) */
  2,	/* (0x2f) */
  5,	/* (0x30) */
  5,	/* (0x31) */
  5,	/* (0x32) */
  5,	/* (0x33) */
  5,	/* (0x34) */
  5,	/* (0x35) */
  5,	/* (0x36) */
  5,	/* (0x37) */
  5,	/* (0x38) */
  5,	/* (0x39) */
  2,	/* (0x3a) */
  2,	/* (0x3b) */
  5,	/* (0x3c) */
  4,	/* (0x3d) */
  5,	/* (0x3e) */
  5,	/* (0x3f) */
  9,	/* (0x40) */
  6,	/* (0x41) */
  6,	/* (0x42) */
  6,	/* (0x43) */
  6,	/* (0x44) */
  6,	/* (0x45) */
  5,	/* (0x46) */
  6,	/* (0x47) */
  6,	/* (0x48) */
  2,	/* (0x49) */
  4,	/* (0x4a) */
  6,	/* (0x4b) */
  5,	/* (0x4c) */
  7,	/* (0x4d) */
  6,	/* (0x4e) */
  6,	/* (0x4f) */
  6,	/* (0x50) */
  6,	/* (0x51) */
  6,	/* (0x52) */
  6,	/* (0x53) */
  4,	/* (0x54) */
  6,	/* (0x55) */
  6,	/* (0x56) */
  7,	/* (0x57) */
  6,	/* (0x58) */
  6,	/* (0x59) */
  6,	/* (0x5a) */
  2,	/* (0x5b) */
  2,	/* (0x5c) */
  2,	/* (0x5d) */
  5,	/* (0x5e) */
  5,	/* (0x5f) */
  3,	/* (0x60) */
  4,	/* (0x61) */
  5,	/* (0x62) */
  4,	/* (0x63) */
  5,	/* (0x64) */
  4,	/* (0x65) */
  3,	/* (0x66) */
  5,	/* (0x67) */
  5,	/* (0x68) */
  2,	/* (0x69) */
  2,	/* (0x6a) */
  4,	/* (0x6b) */
  2,	/* (0x6c) */
  6,	/* (0x6d) */
  5,	/* (0x6e) */
  5,	/* (0x6f) */
  5,	/* (0x70) */
  5,	/* (0x71) */
  3,	/* (0x72) */
  4,	/* (0x73) */
  3,	/* (0x74) */
  4,	/* (0x75) */
  5,	/* (0x76) */
  6,	/* (0x77) */
  5,	/* (0x78) */
  4,	/* (0x79) */
  4,	/* (0x7a) */
  2,	/* (0x7b) */
  2,	/* (0x7c) */
  2,	/* (0x7d) */
  6,	/* (0x7e) */
  6,	/* (0x7f) */
  6,	/* (0x80) */
  6,	/* (0x81) */
  6,	/* (0x82) */
  6,	/* (0x83) */
  6,	/* (0x84) */
  6,	/* (0x85) */
  6,	/* (0x86) */
  6,	/* (0x87) */
  6,	/* (0x88) */
  6,	/* (0x89) */
  6,	/* (0x8a) */
  6,	/* (0x8b) */
  6,	/* (0x8c) */
  6,	/* (0x8d) */
  6,	/* (0x8e) */
  6,	/* (0x8f) */
  6,	/* (0x90) */
  6,	/* (0x91) */
  6,	/* (0x92) */
  6,	/* (0x93) */
  6,	/* (0x94) */
  6,	/* (0x95) */
  6,	/* (0x96) */
  6,	/* (0x97) */
  6,	/* (0x98) */
  6,	/* (0x99) */
  6,	/* (0x9a) */
  6,	/* (0x9b) */
  6,	/* (0x9c) */
  6,	/* (0x9d) */
  6,	/* (0x9e) */
  6,	/* (0x9f) */
  2,	/* (0xa0) */
  6,	/* (0xa1) */
  4,	/* (0xa2) */
  6,	/* (0xa3) */
  4,	/* (0xa4) */
  7,	/* (0xa5) */
  6,	/* (0xa6) */
  5,	/* (0xa7) */
  2,	/* (0xa8) */
  7,	/* (0xa9) */
  6,	/* (0xaa) */
  4,	/* (0xab) */
  6,	/* (0xac) */
  3,	/* (0xad) */
  7,	/* (0xae) */
  6,	/* (0xaf) */
  3,	/* (0xb0) */
  4,	/* (0xb1) */
  3,	/* (0xb2) */
  3,	/* (0xb3) */
  2,	/* (0xb4) */
  4,	/* (0xb5) */
  4,	/* (0xb6) */
  3,	/* (0xb7) */
  2,	/* (0xb8) */
  5,	/* (0xb9) */
  4,	/* (0xba) */
  5,	/* (0xbb) */
  4,	/* (0xbc) */
  5,	/* (0xbd) */
  5,	/* (0xbe) */
  4,	/* (0xbf) */
  6,	/* (0xc0) */
  6,	/* (0xc1) */
  6,	/* (0xc2) */
  6,	/* (0xc3) */
  6,	/* (0xc4) */
  5,	/* (0xc5) */
  6,	/* (0xc6) */
  6,	/* (0xc7) */
  6,	/* (0xc8) */
  6,	/* (0xc9) */
  6,	/* (0xca) */
  6,	/* (0xcb) */
  6,	/* (0xcc) */
  2,	/* (0xcd) */
  2,	/* (0xce) */
  6,	/* (0xcf) */
  6,	/* (0xd0) */
  6,	/* (0xd1) */
  6,	/* (0xd2) */
  6,	/* (0xd3) */
  6,	/* (0xd4) */
  6,	/* (0xd5) */
  6,	/* (0xd6) */
  5,	/* (0xd7) */
  6,	/* (0xd8) */
  6,	/* (0xd9) */
  6,	/* (0xda) */
  6,	/* (0xdb) */
  6,	/* (0xdc) */
  6,	/* (0xdd) */
  4,	/* (0xde) */
  6,	/* (0xdf) */
  3,	/* (0xe0) */
  4,	/* (0xe1) */
  4,	/* (0xe2) */
  4,	/* (0xe3) */
  4,	/* (0xe4) */
  2,	/* (0xe5) */
  4,	/* (0xe6) */
  4,	/* (0xe7) */
  4,	/* (0xe8) */
  4,	/* (0xe9) */
  4,	/* (0xea) */
  4,	/* (0xeb) */
  4,	/* (0xec) */
  2,	/* (0xed) */
  2,	/* (0xee) */
  7,	/* (0xef) */
  5,	/* (0xf0) */
  5,	/* (0xf1) */
  5,	/* (0xf2) */
  5,	/* (0xf3) */
  5,	/* (0xf4) */
  5,	/* (0xf5) */
  5,	/* (0xf6) */
  5,	/* (0xf7) */
  3,	/* (0xf8) */
  4,	/* (0xf9) */
  4,	/* (0xfa) */
  4,	/* (0xfb) */
  4,	/* (0xfc) */
  4,	/* (0xfd) */
  3,	/* (0xfe) */
  3,	/* (0xff) */
};

/* Font structure definition. */
EXTERN_CONST Font font_helvR8 =
{
	/* .glyph  = */ font_helvR8_glyphs,
	/* .name   =    "helvR8", */
	/* .width  = */ 9,
	/* .height = */ 10,
	/* .ascent =    8, */
	/* .first  = */ 0,
	/* .last   = */ 255,
	/* .offset = */ helvR8_offset,
	/* .width  = */ helvR8_width,
};
