/* Generated by convbdf on Fr 8. Jan 02:00:25 CET 2016. */
#include <gfx/font.h>

/* Font information:

   name: -benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1
   pixel size: 10
   ascent: 8
   descent: 2
*/

/* Font character bitmap data. */
static const PROGMEM uint8_t font_lemon_glyphs[] = {

/* Character (0x20): bbw=0, bbh=0, bbx=0, bby=0, width=5 */
0x00, 0x00, 0x00, 0x00, 0x00, /*                                          */
0x00, 0x00, 0x00, 0x00, 0x00, /*                                                    */

/* Character (0x21): bbw=1, bbh=6, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xbc, 0x00, 0x00, /*                   **** *                 */
0x00, 0x00, 0x00, 0x00, 0x00, /*                   **** *                           */

/* Character (0x22): bbw=3, bbh=3, bbx=1, bby=4, width=5 */
0x00, 0x0e, 0x00, 0x0e, 0x00, /*          ***             ***             */
0x00, 0x00, 0x00, 0x00, 0x00, /*          ***             ***                       */

/* Character (0x23): bbw=5, bbh=5, bbx=0, bby=0, width=5 */
0x50, 0xf8, 0x00, 0xf8, 0x50, /*     * *    *****           *****    * *  */
0x00, 0x00, 0x00, 0x00, 0x00, /*     * *    *****           *****    * *            */

/* Character (0x24): bbw=4, bbh=8, bbx=1, bby=-1, width=5 */
0x00, 0x88, 0xf4, 0x9e, 0x64, /*            *   *  * **** ****  *  *  **  */
0x00, 0x00, 0x01, 0x00, 0x00, /*            *   *  * **** ****  *  *  **     *      */

/* Character (0x25): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xcc, 0x20, 0x10, 0xcc, /*           **  **     *      *     **  ** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           **  **     *      *     **  **           */

/* Character (0x26): bbw=5, bbh=6, bbx=0, bby=0, width=5 */
0x68, 0x94, 0xa8, 0x40, 0xa0, /*    * **   * *  *   * * *      *      * * */
0x00, 0x00, 0x00, 0x00, 0x00, /*    * **   * *  *   * * *      *      * *           */

/* Character (0x27): bbw=1, bbh=3, bbx=2, bby=4, width=5 */
0x00, 0x00, 0x0e, 0x00, 0x00, /*                  ***                     */
0x00, 0x00, 0x00, 0x00, 0x00, /*                  ***                               */

/* Character (0x28): bbw=3, bbh=8, bbx=2, bby=-1, width=5 */
0x00, 0x00, 0x78, 0x84, 0x02, /*                    ****   *    * *       */
0x00, 0x00, 0x00, 0x00, 0x01, /*                    ****   *    * *              *  */

/* Character (0x29): bbw=3, bbh=8, bbx=2, bby=-1, width=5 */
0x00, 0x00, 0x02, 0x84, 0x78, /*                  *        *    *   ****  */
0x00, 0x00, 0x01, 0x00, 0x00, /*                  *        *    *   ****     *      */

/* Character (0x2a): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xa8, 0x70, 0x70, 0xa8, /*            * * *    ***     ***    * * * */
0x00, 0x00, 0x00, 0x00, 0x00, /*            * * *    ***     ***    * * *           */

/* Character (0x2b): bbw=5, bbh=5, bbx=0, bby=1, width=5 */
0x10, 0x10, 0x7c, 0x10, 0x10, /*     *       *     *****     *       *    */
0x00, 0x00, 0x00, 0x00, 0x00, /*     *       *     *****     *       *              */

/* Character (0x2c): bbw=2, bbh=3, bbx=1, bby=-1, width=5 */
0x00, 0x00, 0xc0, 0x00, 0x00, /*                       **                 */
0x00, 0x01, 0x00, 0x00, 0x00, /*                       **                  *        */

/* Character (0x2d): bbw=4, bbh=1, bbx=1, bby=3, width=5 */
0x00, 0x10, 0x10, 0x10, 0x10, /*             *       *       *       *    */
0x00, 0x00, 0x00, 0x00, 0x00, /*             *       *       *       *              */

/* Character (0x2e): bbw=1, bbh=2, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xc0, 0x00, 0x00, /*                       **                 */
0x00, 0x00, 0x00, 0x00, 0x00, /*                       **                           */

/* Character (0x2f): bbw=4, bbh=8, bbx=1, bby=-1, width=5 */
0x00, 0x80, 0x60, 0x18, 0x06, /*                *     **    **    **      */
0x00, 0x01, 0x00, 0x00, 0x00, /*                *     **    **    **       *        */

/* Character (0x30): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0xa4, 0x94, 0x78, /*            ****   *  * *  * *  *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *  * *  * *  *   ****            */

/* Character (0x31): bbw=2, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x00, 0x08, 0xfc, 0x00, /*            *      ******                 */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *      ******                           */

/* Character (0x32): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xc4, 0xa4, 0xa4, 0x98, /*           *   **  *  * *  *  * *   **  * */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *   **  *  * *  *  * *   **  *           */

/* Character (0x33): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x84, 0x94, 0x94, 0x68, /*           *    *  * *  *  * *  *   * **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *    *  * *  *  * *  *   * **            */

/* Character (0x34): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x1c, 0x20, 0x20, 0xfc, /*           ***        *       *    ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ***        *       *    ******           */

/* Character (0x35): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x9c, 0x94, 0x94, 0x64, /*           ***  *  * *  *  * *  *  *  **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ***  *  * *  *  * *  *  *  **            */

/* Character (0x36): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x94, 0x94, 0x60, /*            ****   * *  *  * *  *     **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   * *  *  * *  *     **            */

/* Character (0x37): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x04, 0xc4, 0x34, 0x0c, /*           *       *   **  * **    **     */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *       *   **  * **    **               */

/* Character (0x38): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x68, 0x94, 0x94, 0x68, /*            * **   * *  *  * *  *   * **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            * **   * *  *  * *  *   * **            */

/* Character (0x39): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x18, 0xa4, 0xa4, 0x78, /*            **     *  * *  *  * *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            **     *  * *  *  * *   ****            */

/* Character (0x3a): bbw=1, bbh=5, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xd8, 0x00, 0x00, /*                    ** **                 */
0x00, 0x00, 0x00, 0x00, 0x00, /*                    ** **                           */

/* Character (0x3b): bbw=2, bbh=6, bbx=1, bby=-1, width=5 */
0x00, 0x00, 0xd8, 0x00, 0x00, /*                    ** **                 */
0x00, 0x01, 0x00, 0x00, 0x00, /*                    ** **                  *        */

/* Character (0x3c): bbw=3, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x20, 0x50, 0x88, 0x00, /*              *      * *    *   *         */
0x00, 0x00, 0x00, 0x00, 0x00, /*              *      * *    *   *                   */

/* Character (0x3d): bbw=3, bbh=3, bbx=1, bby=2, width=5 */
0x00, 0x28, 0x28, 0x28, 0x00, /*            * *     * *     * *           */
0x00, 0x00, 0x00, 0x00, 0x00, /*            * *     * *     * *                     */

/* Character (0x3e): bbw=3, bbh=5, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x88, 0x50, 0x20, /*                    *   *    * *      *   */
0x00, 0x00, 0x00, 0x00, 0x00, /*                    *   *    * *      *             */

/* Character (0x3f): bbw=3, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x0c, 0xa4, 0x1c, 0x00, /*           **      *  * *  ***            */
0x00, 0x00, 0x00, 0x00, 0x00, /*           **      *  * *  ***                      */

/* Character (0x40): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x84, 0xb4, 0xb8, /*            ****   *    *  * ** *   *** * */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  * ** *   *** *           */

/* Character (0x41): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x24, 0x24, 0xf8, /*            *****  *  *    *  *     ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *****  *  *    *  *     *****           */

/* Character (0x42): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x94, 0x94, 0x68, /*           ******  * *  *  * *  *   * **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******  * *  *  * *  *   * **            */

/* Character (0x43): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x84, 0x84, 0x84, /*            ****   *    *  *    *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  *    *  *    *           */

/* Character (0x44): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x84, 0x84, 0x78, /*           ******  *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******  *    *  *    *   ****            */

/* Character (0x45): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x94, 0x94, 0x84, /*           ******  * *  *  * *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******  * *  *  * *  *  *    *           */

/* Character (0x46): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x14, 0x14, 0x04, /*           ******  * *     * *     *      */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******  * *     * *     *                */

/* Character (0x47): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x84, 0xa4, 0xe4, /*            ****   *    *  *  * *  *  *** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  *  * *  *  ***           */

/* Character (0x48): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x10, 0x10, 0xfc, /*           ******    *       *     ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******    *       *     ******           */

/* Character (0x49): bbw=3, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x84, 0xfc, 0x84, 0x00, /*           *    *  ******  *    *         */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *    *  ******  *    *                   */

/* Character (0x4a): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x40, 0x84, 0x84, 0x7c, /*               *   *    *  *    *  *****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*               *   *    *  *    *  *****            */

/* Character (0x4b): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x10, 0x28, 0xc4, /*           ******    *      * *    *   ** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******    *      * *    *   **           */

/* Character (0x4c): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x80, 0x80, 0x80, /*           ******       *       *       * */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******       *       *       *           */

/* Character (0x4d): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x08, 0x18, 0xfc, /*           ******   *       **     ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******   *       **     ******           */

/* Character (0x4e): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x18, 0x60, 0xfc, /*           ******   **        **   ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******   **        **   ******           */

/* Character (0x4f): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x84, 0x84, 0x78, /*            ****   *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****   *    *  *    *   ****            */

/* Character (0x50): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x24, 0x24, 0x18, /*           ******  *  *    *  *     **    */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******  *  *    *  *     **              */

/* Character (0x51): bbw=4, bbh=7, bbx=1, bby=-1, width=5 */
0x00, 0x78, 0x84, 0x84, 0x78, /*            ****   *    *  *    *   ****  */
0x00, 0x00, 0x00, 0x01, 0x01, /*            ****   *    *  *    *   ****       * *  */

/* Character (0x52): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x24, 0x24, 0xd8, /*           ******  *  *    *  *     ** ** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******  *  *    *  *     ** **           */

/* Character (0x53): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x88, 0x94, 0x94, 0x64, /*            *   *  * *  *  * *  *  *  **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *   *  * *  *  * *  *  *  **            */

/* Character (0x54): bbw=5, bbh=6, bbx=0, bby=0, width=5 */
0x04, 0x04, 0xfc, 0x04, 0x04, /*   *       *       ******  *       *      */
0x00, 0x00, 0x00, 0x00, 0x00, /*   *       *       ******  *       *                */

/* Character (0x55): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x7c, 0x80, 0x80, 0xfc, /*           *****        *       *  ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *****        *       *  ******           */

/* Character (0x56): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x1c, 0xe0, 0xe0, 0x1c, /*           ***        ***     ***  ***    */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ***        ***     ***  ***              */

/* Character (0x57): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x40, 0x40, 0xfc, /*           ******      *       *   ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******      *       *   ******           */

/* Character (0x58): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xec, 0x10, 0x10, 0xec, /*           ** ***    *       *     ** *** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ** ***    *       *     ** ***           */

/* Character (0x59): bbw=5, bbh=6, bbx=0, bby=0, width=5 */
0x04, 0x08, 0xf0, 0x08, 0x04, /*   *        *        ****   *      *      */
0x00, 0x00, 0x00, 0x00, 0x00, /*   *        *        ****   *      *                */

/* Character (0x5a): bbw=4, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0xc4, 0xa4, 0x94, 0x8c, /*           *   **  *  * *  * *  *  **   * */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *   **  *  * *  * *  *  **   *           */

/* Character (0x5b): bbw=3, bbh=8, bbx=1, bby=-1, width=5 */
0x00, 0xfe, 0x02, 0x02, 0x00, /*          ******* *       *               */
0x00, 0x01, 0x01, 0x01, 0x00, /*          ******* *       *                * * *    */

/* Character (0x5c): bbw=4, bbh=8, bbx=1, bby=-1, width=5 */
0x00, 0x06, 0x18, 0x60, 0x80, /*          **        **        **        * */
0x00, 0x00, 0x00, 0x00, 0x01, /*          **        **        **        *        *  */

/* Character (0x5d): bbw=3, bbh=8, bbx=1, bby=-1, width=5 */
0x00, 0x02, 0x02, 0xfe, 0x00, /*          *       *       *******         */
0x00, 0x01, 0x01, 0x01, 0x00, /*          *       *       *******          * * *    */

/* Character (0x5e): bbw=5, bbh=3, bbx=0, bby=4, width=5 */
0x08, 0x04, 0x02, 0x04, 0x08, /*    *      *      *        *        *     */
0x00, 0x00, 0x00, 0x00, 0x00, /*    *      *      *        *        *               */

/* Character (0x5f): bbw=4, bbh=1, bbx=1, bby=-1, width=5 */
0x00, 0x00, 0x00, 0x00, 0x00, /*                                          */
0x00, 0x01, 0x01, 0x01, 0x01, /*                                           * * * *  */

/* Character (0x60): bbw=2, bbh=3, bbx=2, bby=4, width=5 */
0x00, 0x00, 0x06, 0x08, 0x00, /*                  **        *             */
0x00, 0x00, 0x00, 0x00, 0x00, /*                  **        *                       */

/* Character (0x61): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x48, 0xf8, /*             ***    *   *   *  *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *  *    *****           */

/* Character (0x62): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0xfe, 0x88, 0x88, 0x70, /*          *******   *   *   *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *******   *   *   *   *    ***            */

/* Character (0x63): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x88, 0x88, /*             ***    *   *   *   *   *   * */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *   *   *   *           */

/* Character (0x64): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x48, 0xfe, /*             ***    *   *   *  *  ******* */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *  *  *******           */

/* Character (0x65): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x70, 0xa8, 0xa8, 0xb0, /*             ***    * * *   * * *    ** * */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    * * *   * * *    ** *           */

/* Character (0x66): bbw=3, bbh=7, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xfc, 0x0a, 0x0a, /*                   ****** * *     * *     */
0x00, 0x00, 0x00, 0x00, 0x00, /*                   ****** * *     * *               */

/* Character (0x67): bbw=4, bbh=7, bbx=1, bby=-2, width=5 */
0x00, 0x70, 0x88, 0x48, 0xf8, /*             ***    *   *   *  *    ***** */
0x00, 0x00, 0x02, 0x02, 0x01, /*             ***    *   *   *  *    *****     * **  */

/* Character (0x68): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0xfe, 0x08, 0x08, 0xf0, /*          *******   *       *        **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *******   *       *        ****           */

/* Character (0x69): bbw=2, bbh=7, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x08, 0xfa, 0x00, /*                    *     * *****         */
0x00, 0x00, 0x00, 0x00, 0x00, /*                    *     * *****                   */

/* Character (0x6a): bbw=3, bbh=9, bbx=1, bby=-2, width=5 */
0x00, 0x00, 0x08, 0xfa, 0x00, /*                    *     * *****         */
0x00, 0x02, 0x02, 0x01, 0x00, /*                    *     * *****           * **    */

/* Character (0x6b): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0xfe, 0x20, 0x30, 0xc8, /*          *******     *      **     *  ** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *******     *      **     *  **           */

/* Character (0x6c): bbw=2, bbh=7, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x02, 0xfe, 0x00, /*                  *       *******         */
0x00, 0x00, 0x00, 0x00, 0x00, /*                  *       *******                   */

/* Character (0x6d): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x10, 0x30, 0xf8, /*            *****    *       **     ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *****    *       **     *****           */

/* Character (0x6e): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x08, 0x08, 0xf0, /*            *****   *       *        **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *****   *       *        ****           */

/* Character (0x6f): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x88, 0x70, /*             ***    *   *   *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   *   *    ***            */

/* Character (0x70): bbw=4, bbh=7, bbx=1, bby=-2, width=5 */
0x00, 0xf8, 0x88, 0x88, 0x70, /*            *****   *   *   *   *    ***  */
0x00, 0x03, 0x00, 0x00, 0x00, /*            *****   *   *   *   *    ***   **       */

/* Character (0x71): bbw=4, bbh=7, bbx=1, bby=-2, width=5 */
0x00, 0x70, 0x88, 0x88, 0xf8, /*             ***    *   *   *   *   ***** */
0x00, 0x00, 0x00, 0x00, 0x03, /*             ***    *   *   *   *   *****        ** */

/* Character (0x72): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x10, 0x08, 0x08, /*            *****    *      *       *     */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *****    *      *       *               */

/* Character (0x73): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x90, 0xa8, 0xa8, 0x48, /*             *  *   * * *   * * *   *  *  */
0x00, 0x00, 0x00, 0x00, 0x00, /*             *  *   * * *   * * *   *  *            */

/* Character (0x74): bbw=3, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x08, 0x7c, 0x88, 0x00, /*            *      *****    *   *         */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *      *****    *   *                   */

/* Character (0x75): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x78, 0x80, 0x80, 0xf8, /*            ****        *       *   ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****        *       *   *****           */

/* Character (0x76): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x38, 0xc0, 0xc0, 0x38, /*            ***        **      **   ***   */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ***        **      **   ***             */

/* Character (0x77): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x40, 0x40, 0xf8, /*            *****      *       *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *****      *       *    *****           */

/* Character (0x78): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xd8, 0x20, 0x20, 0xd8, /*            ** **     *       *     ** ** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ** **     *       *     ** **           */

/* Character (0x79): bbw=4, bbh=7, bbx=1, bby=-2, width=5 */
0x00, 0x78, 0x80, 0x80, 0xf8, /*            ****        *       *   ***** */
0x00, 0x00, 0x02, 0x02, 0x01, /*            ****        *       *   *****     * **  */

/* Character (0x7a): bbw=4, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0xc8, 0xa8, 0x98, 0x88, /*            *  **   * * *   **  *   *   * */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *  **   * * *   **  *   *   *           */

/* Character (0x7b): bbw=3, bbh=8, bbx=1, bby=-1, width=5 */
0x00, 0x30, 0xfc, 0x02, 0x00, /*             **    ****** *               */
0x00, 0x00, 0x00, 0x01, 0x00, /*             **    ****** *                    *    */

/* Character (0x7c): bbw=1, bbh=10, bbx=2, bby=-2, width=5 */
0x00, 0x00, 0xff, 0x00, 0x00, /*                 ********                 */
0x00, 0x00, 0x03, 0x00, 0x00, /*                 ********                    **     */

/* Character (0x7d): bbw=3, bbh=8, bbx=2, bby=-1, width=5 */
0x00, 0x00, 0x02, 0xfc, 0x30, /*                  *        ******    **   */
0x00, 0x00, 0x01, 0x00, 0x00, /*                  *        ******    **      *      */

/* Character (0x7e): bbw=5, bbh=4, bbx=0, bby=1, width=5 */
0x30, 0x08, 0x30, 0x40, 0x30, /*     **     *        **        *     **   */
0x00, 0x00, 0x00, 0x00, 0x00, /*     **     *        **        *     **             */

/* Character (0x95): bbw=4, bbh=4, bbx=1, bby=0, width=5 */
0x00, 0x60, 0xf0, 0xf0, 0x60, /*              **     ****    ****     **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*              **     ****    ****     **            */

/* Character (0xa1): bbw=3, bbh=6, bbx=1, bby=0, width=5 */
0x00, 0x10, 0xf4, 0x80, 0x00, /*             *     * ****       *         */
0x00, 0x00, 0x00, 0x00, 0x00, /*             *     * ****       *                   */

/* Character (0xa2): bbw=4, bbh=7, bbx=0, bby=-1, width=5 */
0x70, 0x88, 0xf8, 0x8c, 0x00, /*     ***    *   *   *****  **   *         */
0x00, 0x01, 0x00, 0x00, 0x00, /*     ***    *   *   *****  **   *          *        */

/* Character (0xa3): bbw=5, bbh=7, bbx=0, bby=0, width=5 */
0x90, 0xfc, 0x92, 0x82, 0x40, /*     *  *  ****** *  *  * *     *      *  */
0x00, 0x00, 0x00, 0x00, 0x00, /*     *  *  ****** *  *  * *     *      *            */

/* Character (0xa4): bbw=5, bbh=6, bbx=0, bby=0, width=5 */
0x84, 0x78, 0x48, 0x78, 0x84, /*   *    *   ****    *  *    ****   *    * */
0x00, 0x00, 0x00, 0x00, 0x00, /*   *    *   ****    *  *    ****   *    *           */

/* Character (0xa5): bbw=5, bbh=9, bbx=0, bby=-1, width=5 */
0x53, 0x54, 0xf8, 0x54, 0x53, /* **  * *   * * *    *****  * * * **  * *  */
0x00, 0x00, 0x01, 0x00, 0x00, /* **  * *   * * *    *****  * * * **  * *     *      */

/* Character (0xa6): bbw=2, bbh=1, bbx=1, bby=1, width=5 */
0x00, 0x40, 0x40, 0x00, 0x00, /*               *       *                  */
0x00, 0x00, 0x00, 0x00, 0x00, /*               *       *                            */

/* Character (0xa7): bbw=5, bbh=9, bbx=0, bby=-1, width=5 */
0x10, 0x2a, 0x6d, 0xa9, 0x10, /*     *    * * *  * ** ** *  * * *    *    */
0x00, 0x01, 0x01, 0x00, 0x00, /*     *    * * *  * ** ** *  * * *    *     * *      */

/* Character (0xa8): bbw=3, bbh=1, bbx=1, bby=5, width=5 */
0x00, 0x04, 0x00, 0x04, 0x00, /*           *               *              */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *               *                        */

/* Character (0xa9): bbw=6, bbh=7, bbx=0, bby=0, width=5 */
0x38, 0x44, 0xba, 0xaa, 0xaa, /*    ***    *   *  * *** * * * * * * * * * */
0x00, 0x00, 0x00, 0x00, 0x00, /*    ***    *   *  * *** * * * * * * * * *           */

/* Character (0xaa): bbw=4, bbh=4, bbx=1, bby=4, width=5 */
0x00, 0x06, 0x09, 0x09, 0x0f, /*          **     *  *    *  *    ****     */
0x00, 0x00, 0x00, 0x00, 0x00, /*          **     *  *    *  *    ****               */

/* Character (0xab): bbw=4, bbh=3, bbx=1, bby=2, width=5 */
0x00, 0x10, 0x28, 0x10, 0x28, /*             *      * *      *      * *   */
0x00, 0x00, 0x00, 0x00, 0x00, /*             *      * *      *      * *             */

/* Character (0xac): bbw=5, bbh=3, bbx=0, bby=1, width=5 */
0x10, 0x10, 0x10, 0x10, 0x70, /*     *       *       *       *       ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*     *       *       *       *       ***            */

/* Character (0xae): bbw=7, bbh=7, bbx=0, bby=0, width=5 */
0x38, 0x44, 0xba, 0x9a, 0xaa, /*    ***    *   *  * *** * * **  * * * * * */
0x00, 0x00, 0x00, 0x00, 0x00, /*    ***    *   *  * *** * * **  * * * * *           */

/* Character (0xaf): bbw=4, bbh=1, bbx=1, bby=6, width=5 */
0x00, 0x02, 0x02, 0x02, 0x00, /*          *       *       *               */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *       *       *                         */

/* Character (0xb0): bbw=3, bbh=3, bbx=1, bby=3, width=5 */
0x00, 0x08, 0x14, 0x08, 0x00, /*            *      * *      *             */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *      * *      *                       */

/* Character (0xb1): bbw=4, bbh=5, bbx=0, bby=0, width=5 */
0x00, 0x90, 0xb8, 0x90, 0x00, /*             *  *   *** *    *  *         */
0x00, 0x00, 0x00, 0x00, 0x00, /*             *  *   *** *    *  *                   */

/* Character (0xb2): bbw=3, bbh=5, bbx=1, bby=2, width=5 */
0x00, 0x32, 0x2a, 0x24, 0x00, /*          *  **   * * *    *  *           */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  **   * * *    *  *                     */

/* Character (0xb3): bbw=3, bbh=5, bbx=1, bby=2, width=5 */
0x00, 0x2a, 0x2a, 0x14, 0x00, /*          * * *   * * *    * *            */
0x00, 0x00, 0x00, 0x00, 0x00, /*          * * *   * * *    * *                      */

/* Character (0xb4): bbw=2, bbh=2, bbx=1, bby=6, width=5 */
0x00, 0x02, 0x01, 0x00, 0x00, /*          *      *                        */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *      *                                  */

/* Character (0xb5): bbw=4, bbh=6, bbx=0, bby=-1, width=5 */
0xf8, 0x80, 0x80, 0x78, 0x00, /*    *****       *       *   ****          */
0x01, 0x00, 0x00, 0x00, 0x00, /*    *****       *       *   ****         *          */

/* Character (0xb6): bbw=5, bbh=6, bbx=0, bby=0, width=5 */
0x18, 0x24, 0xfc, 0x04, 0xfc, /*    **     *  *    ******  *       ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*    **     *  *    ******  *       ******           */

/* Character (0xb7): bbw=2, bbh=2, bbx=2, bby=2, width=5 */
0x00, 0x00, 0x30, 0x30, 0x00, /*                     **      **           */
0x00, 0x00, 0x00, 0x00, 0x00, /*                     **      **                     */

/* Character (0xb8): bbw=3, bbh=3, bbx=1, bby=1, width=5 */
0x00, 0x40, 0x50, 0x60, 0x00, /*               *     * *      **          */
0x00, 0x00, 0x00, 0x00, 0x00, /*               *     * *      **                    */

/* Character (0xb9): bbw=2, bbh=4, bbx=1, bby=2, width=5 */
0x00, 0x08, 0x3c, 0x00, 0x00, /*            *      ****                   */
0x00, 0x00, 0x00, 0x00, 0x00, /*            *      ****                             */

/* Character (0xba): bbw=4, bbh=4, bbx=0, bby=4, width=5 */
0x06, 0x09, 0x09, 0x06, 0x00, /*  **     *  *    *  *     **              */
0x00, 0x00, 0x00, 0x00, 0x00, /*  **     *  *    *  *     **                        */

/* Character (0xbb): bbw=5, bbh=3, bbx=1, bby=2, width=5 */
0x00, 0x28, 0x10, 0x28, 0x10, /*            * *      *      * *      *    */
0x00, 0x00, 0x00, 0x00, 0x00, /*            * *      *      * *      *              */

/* Character (0xbc): bbw=5, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x02, 0x6f, 0x50, 0xf8, /*          *      **** **     * *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *      **** **     * *    *****           */

/* Character (0xbd): bbw=5, bbh=7, bbx=1, bby=1, width=5 */
0x00, 0x02, 0x0f, 0x48, 0x68, /*          *      ****       *  *    * **  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *      ****       *  *    * **            */

/* Character (0xbe): bbw=6, bbh=8, bbx=0, bby=0, width=5 */
0x11, 0x15, 0x6a, 0x50, 0xf8, /* *   *   * * *    * * **     * *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /* *   *   * * *    * * **     * *    *****           */

/* Character (0xbf): bbw=3, bbh=6, bbx=2, bby=0, width=5 */
0x00, 0x00, 0xe0, 0x94, 0xc0, /*                      ***  * *  *      ** */
0x00, 0x00, 0x00, 0x00, 0x00, /*                      ***  * *  *      **           */

/* Character (0xc0): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x25, 0x26, 0xf8, /*            ****** *  *   **  *     ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****** *  *   **  *     *****           */

/* Character (0xc1): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x26, 0x25, 0xf8, /*            ***** **  *  * *  *     ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ***** **  *  * *  *     *****           */

/* Character (0xc2): bbw=4, bbh=9, bbx=1, bby=0, width=5 */
0x00, 0xf8, 0x25, 0x24, 0xf9, /*            ****** *  *    *  *  *  ***** */
0x00, 0x00, 0x00, 0x02, 0x00, /*            ****** *  *    *  *  *  *****       *   */

/* Character (0xc3): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xfa, 0x25, 0x26, 0xf9, /*          * ****** *  *   **  *  *  ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          * ****** *  *   **  *  *  *****           */

/* Character (0xc4): bbw=5, bbh=8, bbx=0, bby=0, width=5 */
0x00, 0xf9, 0x24, 0x24, 0xf9, /*         *  *****  *  *    *  *  *  ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*         *  *****  *  *    *  *  *  *****           */

/* Character (0xc5): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xfa, 0x25, 0x25, 0xfa, /*          * ****** *  *  * *  *   * ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          * ****** *  *  * *  *   * *****           */

/* Character (0xc6): bbw=6, bbh=6, bbx=0, bby=0, width=5 */
0xf8, 0x24, 0x24, 0xfc, 0x94, /*    *****  *  *    *  *    ******  * *  * */
0x00, 0x00, 0x00, 0x00, 0x00, /*    *****  *  *    *  *    ******  * *  *           */

/* Character (0xc7): bbw=4, bbh=8, bbx=0, bby=-2, width=5 */
0x78, 0x84, 0x84, 0x84, 0x00, /*    ****   *    *  *    *  *    *         */
0x00, 0x02, 0x01, 0x00, 0x00, /*    ****   *    *  *    *  *    *           **      */

/* Character (0xc8): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x95, 0x96, 0x84, /*           ******* * *  * ** *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ******* * *  * ** *  *  *    *           */

/* Character (0xc9): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xfc, 0x96, 0x95, 0x84, /*           ****** ** *  ** * *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ****** ** *  ** * *  *  *    *           */

/* Character (0xca): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xfe, 0x95, 0x96, 0x84, /*          ******** * *  * ** *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, /*          ******** * *  * ** *  *  *    *           */

/* Character (0xcb): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xfd, 0x94, 0x95, 0x84, /*         * ******  * *  ** * *  *  *    * */
0x00, 0x00, 0x00, 0x00, 0x00, /*         * ******  * *  ** * *  *  *    *           */

/* Character (0xcc): bbw=3, bbh=9, bbx=1, bby=0, width=5 */
0x00, 0x84, 0xfd, 0x84, 0x00, /*           *    ** ******  *    *         */
0x00, 0x02, 0x00, 0x00, 0x00, /*           *    ** ******  *    *           *       */

/* Character (0xcd): bbw=3, bbh=9, bbx=1, bby=0, width=5 */
0x00, 0x84, 0xfd, 0x84, 0x00, /*           *    ** ******  *    *         */
0x00, 0x00, 0x00, 0x02, 0x00, /*           *    ** ******  *    *               *   */

/* Character (0xce): bbw=3, bbh=9, bbx=1, bby=0, width=5 */
0x00, 0x85, 0xfc, 0x85, 0x00, /*         * *    *  ******* *    *         */
0x00, 0x00, 0x02, 0x00, 0x00, /*         * *    *  ******* *    *             *     */

/* Character (0xcf): bbw=3, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x85, 0xfc, 0x85, 0x00, /*         * *    *  ******* *    *         */
0x00, 0x00, 0x00, 0x00, 0x00, /*         * *    *  ******* *    *                   */

/* Character (0xd0): bbw=5, bbh=6, bbx=0, bby=0, width=5 */
0x10, 0xfc, 0x94, 0x84, 0x78, /*     *     ******  * *  *  *    *   ****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*     *     ******  * *  *  *    *   ****            */

/* Character (0xd1): bbw=5, bbh=8, bbx=0, bby=0, width=5 */
0x00, 0xfa, 0x09, 0x0a, 0xf1, /*          * ******  *     * *    *   **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          * ******  *     * *    *   ****           */

/* Character (0xd2): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x71, 0x8a, 0x88, 0x70, /*         *   ***  * *   *   *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*         *   ***  * *   *   *   *    ***            */

/* Character (0xd3): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x8a, 0x89, 0x70, /*             ***  * *   **  *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***  * *   **  *   *    ***            */

/* Character (0xd4): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x8a, 0x70, /*          *  *** *  *   * * *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   * * *   *    ***            */

/* Character (0xd5): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x8a, 0x71, /*          *  *** *  *   * * *   **   ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   * * *   **   ***            */

/* Character (0xd6): bbw=5, bbh=7, bbx=0, bby=0, width=5 */
0x00, 0x72, 0x88, 0x88, 0x72, /*          *  ***    *   *   *   * *  ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  ***    *   *   *   * *  ***            */

/* Character (0xd7): bbw=3, bbh=3, bbx=1, bby=2, width=5 */
0x00, 0x28, 0x10, 0x28, 0x00, /*            * *      *      * *           */
0x00, 0x00, 0x00, 0x00, 0x00, /*            * *      *      * *                     */

/* Character (0xd8): bbw=4, bbh=8, bbx=1, bby=-1, width=5 */
0x00, 0x78, 0xe4, 0x9c, 0x7a, /*            ****   *  ***  ***  * * ****  */
0x00, 0x01, 0x00, 0x00, 0x00, /*            ****   *  ***  ***  * * ****   *        */

/* Character (0xd9): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x7d, 0x82, 0x80, 0xfc, /*         * *****  *     *       *  ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*         * *****  *     *       *  ******           */

/* Character (0xda): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x7c, 0x80, 0x82, 0xfd, /*           *****        * *     ** ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           *****        * *     ** ******           */

/* Character (0xdb): bbw=4, bbh=9, bbx=1, bby=0, width=5 */
0x00, 0x7c, 0x81, 0x80, 0xfd, /*           ***** *      *       ** ****** */
0x00, 0x00, 0x00, 0x02, 0x00, /*           ***** *      *       ** ******       *   */

/* Character (0xdc): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x7c, 0x81, 0x80, 0xfd, /*           ***** *      *       ** ****** */
0x00, 0x00, 0x00, 0x00, 0x00, /*           ***** *      *       ** ******           */

/* Character (0xdd): bbw=5, bbh=8, bbx=0, bby=0, width=5 */
0x04, 0x08, 0xf2, 0x09, 0x04, /*   *        *     *  *****  *      *      */
0x00, 0x00, 0x00, 0x00, 0x00, /*   *        *     *  *****  *      *                */

/* Character (0xde): bbw=4, bbh=7, bbx=1, bby=-1, width=5 */
0x00, 0xfc, 0x90, 0x90, 0x60, /*           ******    *  *    *  *     **  */
0x00, 0x01, 0x00, 0x00, 0x00, /*           ******    *  *    *  *     **   *        */

/* Character (0xdf): bbw=4, bbh=7, bbx=1, bby=-1, width=5 */
0x00, 0xf8, 0x04, 0x94, 0x68, /*            *****  *       * *  *   * **  */
0x00, 0x01, 0x00, 0x00, 0x00, /*            *****  *       * *  *   * **   *        */

/* Character (0xe0): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x71, 0x8a, 0x48, 0xf8, /*         *   ***  * *   *   *  *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*         *   ***  * *   *   *  *    *****           */

/* Character (0xe1): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x8a, 0x49, 0xf8, /*             ***  * *   **  *  *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***  * *   **  *  *    *****           */

/* Character (0xe2): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x4a, 0xf8, /*          *  *** *  *   * * *  *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   * * *  *    *****           */

/* Character (0xe3): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x4a, 0xf9, /*          *  *** *  *   * * *  * *  ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   * * *  * *  *****           */

/* Character (0xe4): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x88, 0x48, 0xfa, /*          *  ***    *   *   *  *  * ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  ***    *   *   *  *  * *****           */

/* Character (0xe5): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x4a, 0xf8, /*             ***    *   * * *  *    ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   * * *  *    *****           */

/* Character (0xe6): bbw=5, bbh=5, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x78, 0xa8, /*             ***    *   *   ****    * * * */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   *   ****    * * *           */

/* Character (0xe7): bbw=4, bbh=7, bbx=1, bby=-2, width=5 */
0x00, 0x70, 0x88, 0x88, 0x88, /*             ***    *   *   *   *   *   * */
0x00, 0x00, 0x02, 0x01, 0x00, /*             ***    *   *   *   *   *   *     **    */

/* Character (0xe8): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x71, 0xaa, 0xa8, 0xb0, /*         *   ***  * * * *   * * *    ** * */
0x00, 0x00, 0x00, 0x00, 0x00, /*         *   ***  * * * *   * * *    ** *           */

/* Character (0xe9): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x70, 0xaa, 0xa9, 0xb0, /*             ***  * * * **  * * *    ** * */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***  * * * **  * * *    ** *           */

/* Character (0xea): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0xa9, 0xaa, 0xb0, /*          *  *** *  * * * * * * *    ** * */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  * * * * * * *    ** *           */

/* Character (0xeb): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x72, 0xa8, 0xaa, 0xb0, /*          *  ***    * * * * * * *    ** * */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  ***    * * * * * * *    ** *           */

/* Character (0xec): bbw=2, bbh=8, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x09, 0xfa, 0x00, /*                 *  *     * *****         */
0x00, 0x00, 0x00, 0x00, 0x00, /*                 *  *     * *****                   */

/* Character (0xed): bbw=3, bbh=8, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x08, 0xfa, 0x01, /*                    *     * ******        */
0x00, 0x00, 0x00, 0x00, 0x00, /*                    *     * ******                  */

/* Character (0xee): bbw=3, bbh=8, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x0a, 0xf9, 0x02, /*                  * *    *  ***** *       */
0x00, 0x00, 0x00, 0x00, 0x00, /*                  * *    *  ***** *                 */

/* Character (0xef): bbw=3, bbh=7, bbx=2, bby=0, width=5 */
0x00, 0x00, 0x0a, 0xf8, 0x02, /*                  * *       ***** *       */
0x00, 0x00, 0x00, 0x00, 0x00, /*                  * *       ***** *                 */

/* Character (0xf0): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x75, 0x8a, 0x8b, 0x7c, /*         * * ***  * *   *** *   *  *****  */
0x00, 0x00, 0x00, 0x00, 0x00, /*         * * ***  * *   *** *   *  *****            */

/* Character (0xf1): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0xfa, 0x09, 0x0a, 0xf1, /*          * ******  *     * *    *   **** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          * ******  *     * *    *   ****           */

/* Character (0xf2): bbw=5, bbh=8, bbx=0, bby=0, width=5 */
0x00, 0x71, 0x8a, 0x88, 0x70, /*         *   ***  * *   *   *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*         *   ***  * *   *   *   *    ***            */

/* Character (0xf3): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x70, 0x88, 0x8a, 0x71, /*             ***    *   * * *   **   ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*             ***    *   * * *   **   ***            */

/* Character (0xf4): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x8a, 0x70, /*          *  *** *  *   * * *   *    ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   * * *   *    ***            */

/* Character (0xf5): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x89, 0x8a, 0x71, /*          *  *** *  *   * * *   **   ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  *** *  *   * * *   **   ***            */

/* Character (0xf6): bbw=4, bbh=7, bbx=1, bby=0, width=5 */
0x00, 0x72, 0x88, 0x88, 0x72, /*          *  ***    *   *   *   * *  ***  */
0x00, 0x00, 0x00, 0x00, 0x00, /*          *  ***    *   *   *   * *  ***            */

/* Character (0xf7): bbw=5, bbh=5, bbx=0, bby=1, width=5 */
0x10, 0x10, 0x54, 0x10, 0x10, /*     *       *     * * *     *       *    */
0x00, 0x00, 0x00, 0x00, 0x00, /*     *       *     * * *     *       *              */

/* Character (0xf8): bbw=4, bbh=7, bbx=1, bby=-1, width=5 */
0x00, 0x70, 0xc8, 0x98, 0x74, /*             ***    *  **   **  *  * ***  */
0x00, 0x01, 0x00, 0x00, 0x00, /*             ***    *  **   **  *  * ***   *        */

/* Character (0xf9): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x79, 0x82, 0x80, 0xf8, /*         *  ****  *     *       *   ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*         *  ****  *     *       *   *****           */

/* Character (0xfa): bbw=5, bbh=8, bbx=0, bby=0, width=5 */
0x00, 0x78, 0x82, 0x81, 0xf8, /*            ****  *     **      *   ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*            ****  *     **      *   *****           */

/* Character (0xfb): bbw=4, bbh=8, bbx=1, bby=0, width=5 */
0x00, 0x7a, 0x81, 0x82, 0xf8, /*          * **** *      * *     *   ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          * **** *      * *     *   *****           */

/* Character (0xfc): bbw=5, bbh=7, bbx=0, bby=0, width=5 */
0x00, 0x7a, 0x80, 0x82, 0xf8, /*          * ****        * *     *   ***** */
0x00, 0x00, 0x00, 0x00, 0x00, /*          * ****        * *     *   *****           */

/* Character (0xfd): bbw=4, bbh=10, bbx=1, bby=-2, width=5 */
0x00, 0x78, 0x82, 0x81, 0xf8, /*            ****  *     **      *   ***** */
0x00, 0x00, 0x02, 0x02, 0x01, /*            ****  *     **      *   *****     * **  */

/* Character (0xfe): bbw=4, bbh=9, bbx=1, bby=-2, width=5 */
0x00, 0xfe, 0x88, 0x88, 0x70, /*          *******   *   *   *   *    ***  */
0x00, 0x03, 0x00, 0x00, 0x00, /*          *******   *   *   *   *    ***   **       */

/* Character (0xff): bbw=4, bbh=9, bbx=1, bby=-2, width=5 */
0x00, 0x78, 0x82, 0x80, 0xfa, /*            ****  *     *       * * ***** */
0x00, 0x00, 0x02, 0x02, 0x01, /*            ****  *     *       * * *****     * **  */
};

/* Font structure definition. */
EXTERN_CONST Font font_lemon =
{
	/* .glyph  = */ font_lemon_glyphs,
	/* .name   =    "lemon", */
	/* .width  = */ 5,
	/* .height = */ 10,
	/* .ascent =    8, */
	/* .first  = */ 32,
	/* .last   = */ 255,
	/* .offset = */ NULL,
	/* .width  = */ NULL,
};
